extends Node

## English message IDs; proper names of arts, items and realms stay consistent.
const INDONESIAN: Dictionary = {

	"Call unlocked equipment. Pity and Wish Fate persist across sessions.": "Panggil perlengkapan yang telah terbuka. Pity dan Takdir Wish tersimpan antar sesi.",
	"PERMANENT ARMORY • WISH ENABLED": "GUDANG SENJATA PERMANEN • WISH AKTIF",
	"SELECT A LEGENDARY WISH • OR SUMMON THE OPEN POOL": "PILIH WISH LEGENDARIS • ATAU PANGGIL DARI POOL TERBUKA",
	"PITY": "PITY",
	"GUARANTEE TRACKS": "JALUR JAMINAN",
	"GUARANTEE": "JAMINAN",
	"GUARANTEED IN %d": "DIJAMIN DALAM %d",
	"UNLOCK LEGENDARY": "BUKA LEGENDARIS",
	"Choose one unlocked Legendary. Miss once and Wish Fate guarantees the next Legendary target.": "Pilih satu Legendaris yang telah terbuka. Sekali meleset membuat Takdir Wish menjamin target Legendaris berikutnya.",
	"WISH FATE ACTIVE • NEXT LEGENDARY IS GUARANTEED TO MATCH YOUR TARGET": "TAKDIR WISH AKTIF • LEGENDARIS BERIKUTNYA DIJAMIN SESUAI TARGET",
	"NO WISH TARGET • ALL UNLOCKED EQUIPMENT SHARE THE POOL": "TANPA TARGET WISH • SEMUA PERLENGKAPAN TERBUKA BERBAGI POOL",
	"WISH TARGET • 50% LEGENDARY PREFERENCE": "TARGET WISH • PREFERENSI LEGENDARIS 50%",
	"LEGENDARY WISH TARGETS APPEAR AS YOUR JOURNEY UNLOCKS THEM": "TARGET WISH LEGENDARIS MUNCUL SAAT PERJALANANMU MEMBUKANYA",
	"SET WISH": "PASANG WISH",
	"CLEAR": "HAPUS",
	"OPEN": "TERBUKA",
	"CLEAR CHAPTER 1-5 TO AWAKEN THE ARMORY": "TUNTASKAN BAB 1-5 UNTUK MEMBANGKITKAN GUDANG SENJATA",
	"SUMMON ×%d": "PANGGIL ×%d",
	"%d PAVILION SEAL%s": "%d SEGEL PAVILIUN%s",
	"%d CELESTIAL JADE": "%d GIOK LANGIT",
	" • SAVE 10%": " • HEMAT 10%",
	"A CELESTIAL RELIC ANSWERED YOUR CALL": "RELIK LANGIT MENJAWAB PANGGILANMU",
	"THE ARMORY RESONATES WITH RARE QI": "GUDANG SENJATA BERESONANSI DENGAN QI LANGKA",
	"THE ARMORY HAS ANSWERED": "GUDANG SENJATA TELAH MENJAWAB",
	"Celestial Jade purchase remains unavailable until verified platform billing is integrated.": "Pembelian Giok Langit tetap tidak tersedia sampai billing platform yang terverifikasi terintegrasi.",
	"CELESTIAL PAVILION": "PAVILIUN LANGIT",
	"Equipment Summon": "Panggilan Perlengkapan",
	"Call unlocked equipment from the Celestial Armory. Pity and Wish Fate persist across sessions.": "Panggil perlengkapan yang telah terbuka dari Gudang Senjata Langit. Pity dan Takdir Wish tersimpan antar sesi.",
	"LOCKED • CLEAR CHAPTER 1-5": "TERKUNCI • TUNTASKAN BAB 1-5",
	"OPEN • UNLOCKED EQUIPMENT ONLY": "TERBUKA • HANYA PERLENGKAPAN YANG TELAH TERBUKA",
	"SUMMON RITUAL": "RITUAL PANGGILAN",
	"CELESTIAL ARMORY SEALED": "GUDANG SENJATA LANGIT TERSEGEL",
	"CELESTIAL ARMORY": "GUDANG SENJATA LANGIT",
	"Clear Chapter 1-5 to unlock equipment summoning.": "Tuntaskan Bab 1-5 untuk membuka pemanggilan perlengkapan.",
	"Summon unlocked equipment • Pavilion Seals are consumed before Celestial Jade.": "Panggil perlengkapan yang telah terbuka • Segel Paviliun digunakan sebelum Giok Langit.",
	"CLAIM INITIATE GIFT • 10 PAVILION SEALS": "AMBIL HADIAH INISIASI • 10 SEGEL PAVILIUN",
	"LIFETIME SUMMONS": "TOTAL PANGGILAN",
	"PAYMENT PRIORITY": "PRIORITAS PEMBAYARAN",
	"SEAL → JADE": "SEGEL → GIOK",
	"PITY PROGRESS": "PROGRES PITY",
	"RARE+": "LANGKA+",
	"EPIC+": "EPIK+",
	"%d / %d • GUARANTEED IN %d": "%d / %d • DIJAMIN DALAM %d",
	"PAUSED • UNLOCK A LEGENDARY POOL": "DIJEDA • BUKA POOL LEGENDARIS",
	"LEGENDARY WISH": "WISH LEGENDARIS",
	"Choose an unlocked Legendary. A miss awakens Fate; the next Legendary is guaranteed to be that target.": "Pilih Legendaris yang telah terbuka. Sekali meleset membangkitkan Takdir; Legendaris berikutnya dijamin menjadi target itu.",
	"WISH FATE ACTIVE • The next Legendary is guaranteed to be the current target.": "TAKDIR WISH AKTIF • Legendaris berikutnya dijamin menjadi target saat ini.",
	"NO LEGENDARY WISH": "TANPA WISH LEGENDARIS",
	"SELECT A LEGENDARY TARGET": "PILIH TARGET LEGENDARIS",
	"FATE GUARANTEED • NEXT LEGENDARY IS THIS TARGET": "TAKDIR DIJAMIN • LEGENDARIS BERIKUTNYA ADALAH TARGET INI",
	"50% TARGET RATE • MISS ONCE TO AWAKEN FATE": "PELUANG TARGET 50% • SEKALI MELESET MEMBANGKITKAN TAKDIR",
	"WISH TARGETS UNLOCK WITH LEGENDARY EQUIPMENT": "TARGET WISH TERBUKA BERSAMA PERLENGKAPAN LEGENDARIS",
	"CLEAR WISH": "HAPUS WISH",
	"HEAVENLY RESONANCE • LEGENDARY": "RESONANSI LANGIT • LEGENDARIS",
	"CELESTIAL RESONANCE • EPIC": "RESONANSI LANGIT • EPIK",
	"CELESTIAL RESONANCE ANSWERED": "RESONANSI LANGIT MENJAWAB",
	"SUMMON REVEAL": "HASIL PANGGILAN",
	"NEW %d • DUPLICATES %d • +%d SHARDS": "BARU %d • DUPLIKAT %d • +%d PECAHAN",
	"CELESTIAL LEGENDARY REVEAL": "PENAMPAKAN LEGENDARIS LANGIT",
	"DUPLICATE → +%d SHARDS": "DUPLIKAT → +%d PECAHAN",
	"NEW EQUIPMENT": "PERLENGKAPAN BARU",
	"LEGENDARY PITY": "PITY LEGENDARIS",
	"WISH FATE AWAKENED": "TAKDIR WISH BANGKIT",
	"WISH FATE • TARGET": "TAKDIR WISH • TARGET",
	"SAVE FAILED • TRY AGAIN": "GAGAL MENYIMPAN • COBA LAGI",
	"Your run is still open. Free device storage or retry saving before leaving.": "Sesi masih terbuka. Kosongkan penyimpanan perangkat atau coba simpan lagi sebelum keluar.",
	"HOME": "BERANDA",
	"CULTIVATE": "KULTIVASI",
	"HERO": "HERO",
	"TRIALS": "UJIAN",
	"PAVILION": "PAVILIUN",
	"JADE SANCTUARY": "PESANGGRAHAN GIOK",
	"Your path to ascension": "Jalanmu menuju keabadian",
	"CONTINUE RUN": "LANJUTKAN",
	"ENTER JOURNEY": "MULAI PERJALANAN",
	"DAILY TRIALS": "UJIAN HARIAN",
	"ACHIEVEMENTS": "PENCAPAIAN",
	"%d / %d trials cleared  •  Your path to ascension": "%d / %d ujian tuntas  •  Jalan menuju keabadian",
	"CHAPTER COMPLETE  •  Revisit any trial in Journey": "BAB TUNTAS  •  Ulangi ujian melalui Perjalanan",
	"CONTINUE  •  %s": "LANJUTKAN  •  %s",
	"CONTINUE  •  STAGE %d-%d": "LANJUTKAN  •  UJIAN %d-%d",
	"‹  HOME": "‹  BERANDA",
	"‹   BACK": "‹   KEMBALI",
	"PREFERENCES": "PREFERENSI",
	"Settings": "Pengaturan",
	"Audio mixing • saved automatically on this device": "Volume • tersimpan otomatis di perangkat",
	"AUDIO MIXER": "PENGATURAN AUDIO",
	"Spiritual Resonance": "Resonansi Spiritual",
	"MUSIC & SOUND": "MUSIK & SUARA",
	"Master Volume": "Volume Utama",
	"Controls the final output of every audio channel.": "Mengatur volume seluruh suara.",
	"Music": "Musik",
	"Controls music routed through the Music channel.": "Mengatur volume musik latar.",
	"Sound Effects": "Efek Suara",
	"Controls combat, interface, and world effects routed to SFX.": "Mengatur suara pertempuran, tombol, dan lingkungan.",
	"Applied instantly • saved automatically on this device.": "Langsung diterapkan • tersimpan otomatis di perangkat.",
	"RESTORE AUDIO DEFAULTS": "PULIHKAN VOLUME AWAL",
	"COMFORT & LANGUAGE": "KENYAMANAN & BAHASA",
	"Screen shake": "Guncangan layar",
	"Reduced flashes and effects": "Kurangi kilatan dan efek",
	"Damage numbers": "Angka kerusakan",
	"Vibration": "Getaran",
	"60 FPS • Smooth": "60 FPS • Gerakan halus",
	"30 FPS • Battery saver": "30 FPS • Hemat baterai",
	"Sound is temporarily unavailable.": "Suara sementara tidak tersedia.",
	"PRIVACY & SUPPORT": "PRIVASI & BANTUAN",
	"Your journey stays on your device.": "Perjalananmu tersimpan di perangkatmu.",
	"This offline edition does not send gameplay data, personal information, or device identifiers to a server. It has no account, advertising, analytics service, or real-money purchases.": "Edisi luring ini tidak mengirim data permainan, informasi pribadi, atau pengenal perangkat ke server. Tidak ada akun, iklan, layanan analitik, atau pembelian dengan uang nyata.",
	"What the game saves": "Data yang disimpan",
	"Progress, equipment, achievements, daily trials, run checkpoints, and preferences are stored locally. Daily trials and meditation use your device date. Auras change appearance only.": "Progres, perlengkapan, pencapaian, ujian harian, checkpoint, dan preferensi disimpan secara lokal. Ujian harian dan meditasi memakai tanggal perangkat. Aura hanya mengubah penampilan.",
	"Deleting your data": "Menghapus data",
	"On Android, use Settings > Apps > Jade Ascendant > Storage > Clear storage, or uninstall the game. This removes local progress. This edition has no cloud save or account recovery.": "Di Android, buka Pengaturan > Aplikasi > Jade Ascendant > Penyimpanan > Hapus data, atau copot game. Progres lokal akan terhapus. Edisi ini tidak memiliki simpanan awan atau pemulihan akun.",
	"Optional vibration": "Getaran opsional",
	"Vibration can be enabled in Settings. It only provides feedback during combat and does not collect data.": "Getaran dapat diaktifkan di Pengaturan. Fungsinya memberi respons saat bertempur dan tidak mengumpulkan data.",
	"External links and support": "Tautan luar dan bantuan",
	"Opening the policy or support link uses an external browser or email app. Information you choose to send for support is handled by the publisher under the published privacy policy.": "Tautan kebijakan atau bantuan membuka peramban atau aplikasi surel. Informasi yang kamu kirim untuk bantuan ditangani penerbit sesuai kebijakan privasi yang diterbitkan.",
	"OPEN PRIVACY POLICY": "BUKA KEBIJAKAN PRIVASI",
	"CONTACT SUPPORT": "HUBUNGI BANTUAN",
	"BACK TO SETTINGS": "KEMBALI KE PENGATURAN",
	"JADE PAVILION": "PAVILIUN GIOK",
	"Rest, gather your Qi, and prepare for the next trial.": "Beristirahat, himpun Qi, dan bersiap menghadapi ujian berikutnya.",
	"Daily Meditation": "Meditasi Harian",
	"A quiet moment grants 20 Spirit Stones once per local day.": "Meditasi memberikan 20 Batu Roh sekali sehari menurut tanggal perangkat.",
	"MEDITATE  •  +20 SPIRIT STONES": "MEDITASI  •  +20 BATU ROH",
	"MEDITATED TODAY": "SUDAH MEDITASI HARI INI",
	"Cultivation Auras": "Aura Kultivasi",
	"Complete trials to unlock auras. These change appearance only.": "Tuntaskan ujian untuk membuka aura. Aura hanya mengubah penampilan.",
	"Equipment Forge": "Penempaan Perlengkapan",
	"Exchange earned Spirit Stones or Refinement Shards for equipment. Duplicate rewards become shards automatically.": "Tukar Batu Roh atau Pecahan Pemurnian hasil bermain dengan perlengkapan. Hadiah duplikat otomatis menjadi pecahan.",
	"About Jade Ascendant": "Tentang Jade Ascendant",
	"This edition plays offline. All equipment is earned through play. No ads or real-money purchases are included.": "Edisi ini dimainkan luring. Semua perlengkapan diperoleh melalui permainan. Tidak ada iklan atau pembelian dengan uang nyata.",
	"%d Spirit Stones  •  %d Refinement Shards": "%d Batu Roh  •  %d Pecahan Pemurnian",
	"  •  Clear 1-%d": "  •  Tuntaskan 1-%d",
	"A save needs recovery. Close and reopen the game before continuing.": "Simpanan perlu dipulihkan. Tutup dan buka kembali game sebelum melanjutkan.",
	"Finish the current run to use the forge.": "Selesaikan sesi yang berjalan untuk memakai penempaan.",
	"OWNED  •  Equip from Hero": "DIMILIKI  •  Pasang melalui Hero",
	"Unlock after clearing trial 1-%d": "Terbuka setelah menuntaskan ujian 1-%d",
	"EXCHANGE  •  %d SPIRIT STONES": "TUKAR  •  %d BATU ROH",
	"FORGE  •  %d REFINEMENT SHARDS": "TEMPA  •  %d PECAHAN PEMURNIAN",
	"Meditation complete. +20 Spirit Stones.": "Meditasi selesai. +20 Batu Roh.",
	"Aura selected.": "Aura dipilih.",
	"Equipment acquired. Open Hero to equip it.": "Perlengkapan diperoleh. Buka Hero untuk memasangnya.",
	"Common": "Umum",
	"Rare": "Langka",
	"Epic": "Epik",
	"Legendary": "Legendaris",
	"damage": "kerusakan",
	"speed": "kecepatan",
	"critical chance": "peluang kritis",
	"Plain Robes": "Tanpa Aura",
	"Jade Aura": "Aura Giok",
	"Golden Aura": "Aura Emas",
	"JOURNEY   •   REALMS": "PERJALANAN   •   ALAM",
	"CELESTIAL JOURNEY": "PERJALANAN LANGIT",
	"SELECT CHAPTER": "PILIH BAB",
	"VALLEY OF AWAKENING": "LEMBAH KEBANGKITAN",
	"Choose a cultivation realm and continue the path toward ascension.": "Pilih alam kultivasi dan lanjutkan perjalanan menuju keabadian.",
	"AVAILABLE REALMS": "ALAM TERSEDIA",
	"ASCENSION PATH": "JALAN KEABADIAN",
	"Unlocked realms can be revisited. Cleared progress is permanent.": "Alam yang terbuka dapat diulang. Progres penyelesaian bersifat permanen.",
	"JOURNEY   •   TRIALS": "PERJALANAN   •   UJIAN",
	"CHAPTER": "BAB",
	"CHAPTER %02d": "BAB %02d",
	"CULTIVATION REALM": "ALAM KULTIVASI",
	"SELECT A TRIAL AND CONTINUE YOUR ASCENSION": "PILIH UJIAN DAN LANJUTKAN JALAN KEABADIAN",
	"REALM TRIALS": "UJIAN ALAM",
	"PROGRESS IS PERMANENT": "PROGRES BERSIFAT PERMANEN",
	"SELECTED TRIAL": "UJIAN TERPILIH",
	"No playable stage selected": "Belum ada ujian yang dipilih",
	"BEGIN TRIAL": "MULAI UJIAN",
	"SELECTED": "TERPILIH",
	"CLEARED": "TUNTAS",
	"AVAILABLE": "TERSEDIA",
	"LOCKED": "TERKUNCI",
	"UNAVAILABLE": "TIDAK TERSEDIA",
	"FIRST CLEAR": "PENYELESAIAN PERTAMA",
	"REPEAT CLEAR": "PENYELESAIAN ULANG",
	"First Clear Reward": "Hadiah Penyelesaian Pertama",
	"Repeat Clear Reward": "Hadiah Penyelesaian Ulang",
	"Stage Clear Reward": "Hadiah Ujian",
	"Boss Reward": "Hadiah Penjaga",
	"FIRST CLEAR • PROGRESS RECORDED": "PERTAMA TUNTAS • PROGRES TERSIMPAN",
	"REPEAT CLEAR • REWARD SECURED": "ULANG TUNTAS • HADIAH TERSIMPAN",
	"STAGE CLEAR • REWARD SECURED": "UJIAN TUNTAS • HADIAH TERSIMPAN",
	"TRIAL HALL  •  DAILY DISCIPLINES": "BALAI UJIAN  •  DISIPLIN HARIAN",
	"JADE TRIAL HALL • CULTIVATION RECORDS": "BALAI UJIAN GIOK • CATATAN KULTIVASI",
	"Daily Trials": "Ujian Harian",
	"DAILY CYCLE": "SIKLUS HARIAN",
	"DAILY": "HARIAN",
	"COMPLETED": "SELESAI",
	"REWARDS READY": "HADIAH SIAP",
	"NO REWARDS": "BELUM ADA HADIAH",
	"DAILY CYCLE PROGRESS": "PROGRES SIKLUS HARIAN",
	"%d / %d COMPLETE": "%d / %d SELESAI",
	"Complete every daily discipline to finish today's trial cycle.": "Selesaikan seluruh disiplin harian untuk menuntaskan siklus hari ini.",
	"TRIAL HALL  •  ETERNAL RECORDS": "BALAI UJIAN  •  CATATAN ABADI",
	"Achievement Records": "Catatan Pencapaian",
	"ETERNAL RECORDS": "CATATAN ABADI",
	"ETERNAL RECORDS  •  %d DISCOVERED": "CATATAN ABADI  •  %d TERBUKA",
	"DISCOVERED": "TERBUKA",
	"REWARD  •  %d SPIRIT STONE": "HADIAH  •  %d BATU ROH",
	"CLAIMED": "DIAMBIL",
	"CLAIM REWARD": "AMBIL HADIAH",
	"CLAIM ALL": "AMBIL SEMUA",
	"CLAIM ALL (%d)": "AMBIL SEMUA (%d)",
	"IN PROGRESS": "BERLANGSUNG",
	"CULTIVATION": "KULTIVASI",
	"SACRED MERIDIAN FORMATION": "FORMASI MERIDIAN SUCI",
	"INNER SEA  •  PERMANENT CULTIVATION": "LAUTAN BATIN  •  KULTIVASI PERMANEN",
	"Sacred Cultivation Formation": "Formasi Kultivasi Suci",
	"MERIDIAN MASTERY %d / %d": "PENGUASAAN MERIDIAN %d / %d",
	"BODY MERIDIAN": "MERIDIAN TUBUH",
	"Vitality": "Vitalitas",
	"Strengthen the body and expand the vessel of qi.": "Perkuat tubuh dan perluas wadah Qi.",
	"Refine sword intent into permanent spiritual power.": "Murnikan tekad pedang menjadi kekuatan spiritual permanen.",
	"CURRENT EFFECT": "EFEK SAAT INI",
	"NEXT REFINEMENT": "PEMURNIAN BERIKUTNYA",
	"LEVEL %d / %d": "LEVEL %d / %d",
	"REFINE MERIDIAN": "MURNIKAN MERIDIAN",
	"MERIDIAN PERFECTED": "MERIDIAN SEMPURNA",
	"This meridian has reached its current limit.": "Meridian ini telah mencapai batasnya.",
	"Need %d more Spirit Stones.": "Perlu %d Batu Roh lagi.",
	"Permanent upgrade • persists between journeys.": "Peningkatan permanen • tetap ada antarperjalanan.",
	"+%d MAX HP": "+%d HP MAKS",
	"+%d%% POWER": "+%d%% DAYA",
	"%.3f ATTACKS/S": "%.3f SERANGAN/DETIK",
	"PERFECTED": "SEMPURNA",
	"MARTIAL LOADOUT  •  JADE PAVILION": "PERLENGKAPAN BELA DIRI  •  PAVILIUN GIOK",
	"WANDERING CULTIVATOR  •  MARTIAL RESONANCE": "KULTIVATOR PENGEMBARA  •  RESONANSI BELA DIRI",
	"WANDERING CULTIVATOR": "KULTIVATOR PENGEMBARA",
	"MERIDIAN DISCIPLE": "MURID MERIDIAN",
	"JADE ADEPT": "AHLI GIOK",
	"DAO MASTER": "MAHA GURU DAO",
	"ASCENDANT": "ASCENDANT",
	"HEAVENLY ASCENDANT": "ASCENDANT LANGIT",
	"%d HERO EXP": "%d EXP LIN YUE",
	"EQUIPPED %d / 4": "TERPASANG %d / 4",
	"LOADOUT READY": "PERLENGKAPAN SIAP",
	"EQUIPMENT": "PERLENGKAPAN",
	"BACKPACK": "TAS",
	"EQUIPPED GEAR": "PERLENGKAPAN TERPASANG",
	"ROBE": "JUBAH",
	"BRACER": "PELINDUNG LENGAN",
	"PENDANT": "LIONTIN",
	"BOOTS": "SEPATU",
	"EMPTY SLOT": "SLOT KOSONG",
	"EQUIP ITEM": "PASANG",
	"UNEQUIP ITEM": "LEPAS",
	"AVAILABLE EQUIPMENT FOR THIS SLOT": "PERLENGKAPAN UNTUK SLOT INI",
	"Equipment changes are saved permanently outside active runs.": "Perubahan perlengkapan tersimpan permanen di luar sesi aktif.",
	"BACKPACK  •  EQUIPMENT INVENTORY": "TAS  •  INVENTARIS PERLENGKAPAN",
	"Martial Backpack": "Tas Bela Diri",
	"OWNED EQUIPMENT": "PERLENGKAPAN DIMILIKI",
	"Your martial backpack is empty.": "Tas bela dirimu masih kosong.",
	"LOADOUT": "PERLENGKAPAN",
	"MY EQUIPMENT  •  TAP AN ITEM FOR DETAILS": "PERLENGKAPAN SAYA  •  KETUK ITEM UNTUK DETAIL",
	"INVENTORY  •  TAP AN ITEM FOR DETAILS": "INVENTARIS  •  KETUK ITEM UNTUK DETAIL",
	"ALL": "SEMUA",
	"GEAR": "PAKAI",
	"MATERIAL": "BAHAN",
	"SORT  •  %s": "URUT  •  %s",
	"SORT  •  RARITY": "URUT  •  RARITAS",
	"EQUIP %s": "PASANG %s",
	"CLOUDSTEP": "LANGKAH AWAN",
	"SLOT": "SLOT",
	"NAME": "NAMA",
	"NO ITEM SELECTED": "BELUM ADA ITEM DIPILIH",
	"Choose an item from the backpack grid.": "Pilih item dari grid tas.",
	"NO ACTION": "TIDAK ADA AKSI",
	"Tap × to return to the inventory grid.": "Ketuk × untuk kembali ke grid inventaris.",
	"Tap × to return to the equipment grid.": "Ketuk × untuk kembali ke grid perlengkapan.",
	"LOADOUT READY  •  SELECT A SLOT TO ATTUNE": "PERLENGKAPAN SIAP  •  PILIH SLOT",
	"Remove this item from the permanent loadout.": "Lepas item ini dari perlengkapan permanen.",
	"Inspect it here; forge or acquire it before equipping.": "Periksa item ini; tempa atau dapatkan sebelum memasangnya.",
	"Applies immediately and saves outside active runs.": "Langsung diterapkan dan tersimpan di luar sesi aktif.",
	"REFINEMENT MATERIAL  •  OWNED x%d": "BAHAN PEMURNIAN  •  DIMILIKI x%d",
	"PAVILION RESOURCE": "SUMBER DAYA PAVILIUN",
	"OPEN JADE PAVILION": "BUKA PAVILIUN GIOK",
	"Use Refinement Shards to forge unlocked equipment.": "Gunakan Pecahan Pemurnian untuk menempa perlengkapan yang terbuka.",
	"Equip directly without leaving the backpack.": "Pasang langsung tanpa meninggalkan tas.",
	"COMMON": "UMUM",
	"RARE": "LANGKA",
	"EPIC": "EPIK",
	"LEGENDARY": "LEGENDARIS",
	"ASCENSION LOCKED": "ASCENSION TERKUNCI",
	"ASCENSION SEALED": "ASCENSION DISEGEL",
	"MAX ASCENSION": "ASCENSION MAKS",
	"MAX ASCENSION  •  CORE PASSIVE +20% FROM 1★": "ASCENSION MAKS  •  PASIF DASAR +20% DARI 1★",
	"NEXT %d★  •  %s": "BERIKUTNYA %d★  •  %s",
	"ASCEND TO %d★  •  %d SHARDS": "NAIK KE %d★  •  %d PECAHAN",
	"Need %d more Refinement Shards.": "Perlu %d Pecahan Pemurnian lagi.",
	"Acquire this equipment before ascending it.": "Dapatkan perlengkapan ini sebelum menaikkan bintangnya.",
	"Finish or clear the active run before ascending equipment.": "Selesaikan sesi aktif sebelum menaikkan bintang perlengkapan.",
	"Ascension strengthens core passives only; Signature Effects stay fixed.": "Ascension hanya memperkuat pasif dasar; Efek Ciri Khas tetap.",
	"This equipment has reached 5★.": "Perlengkapan ini telah mencapai 5★.",
	"SKIP": "LEWATI",
	"SPIRITUAL BREAKTHROUGH • RUN CULTIVATION": "TEROBOSAN SPIRITUAL • KULTIVASI SESI",
	"CHOOSE YOUR PATH": "PILIH JALURMU",
	"One insight will shape the rest of this run.": "Satu pemahaman akan membentuk sisa sesi ini.",
	"Choose one path. The battlefield resumes immediately after selection.": "Pilih satu jalur. Pertempuran langsung berlanjut setelah pilihan ditetapkan.",
	"Refine this cultivation path for the current run.": "Murnikan jalur kultivasi ini untuk sesi berjalan.",
	"NEW • LV.1": "BARU • LV.1",
	"ACTIVE RUN • CULTIVATION SEALED": "SESI AKTIF • KULTIVASI TERKUNCI",
	"BATTLE PAUSED": "PERTEMPURAN DIJEDA",
	"Gather your focus. The battlefield remains sealed until you resume.": "Himpun fokusmu. Medan tetap tersegel sampai kamu melanjutkan.",
	"RESUME BATTLE": "LANJUTKAN PERTEMPURAN",
	"SAVE & RETURN HOME": "SIMPAN & KEMBALI KE BERANDA",
	"Returning home preserves the active-run checkpoint.": "Kembali ke beranda mempertahankan checkpoint sesi aktif.",
	"DAO HEART SHAKEN • RUN ENDED": "HATI DAO TERGUNCANG • SESI BERAKHIR",
	"FALLEN IN BATTLE": "GUGUR DALAM PERTEMPURAN",
	"REWARD RECOVERED": "HADIAH DIPULIHKAN",
	"REKINDLE • RETRY": "BANGKIT KEMBALI • COBA LAGI",
	"Retry begins the selected stage from the start. Permanent progression remains intact.": "Coba Lagi memulai ujian terpilih dari awal. Progres permanen tetap tersimpan.",
	"Reflect, refine, and rise again": "Renungkan, murnikan, lalu bangkit kembali",
	"STAGE CLEAR • DAO PATH ADVANCED": "UJIAN TUNTAS • JALAN DAO BERLANJUT",
	"REWARDS SECURED": "HADIAH TERSIMPAN",
	"The run is complete. Rewards are already secured before leaving the battlefield.": "Sesi telah selesai. Hadiah sudah tersimpan sebelum meninggalkan medan pertempuran.",
	"CULTIVATE  •  TRANSCEND  •  ASCEND": "KULTIVASI  •  MELAMPAUI  •  MENCAPAI KEABADIAN",
	"CELESTIAL TRANSIT": "PERJALANAN LANGIT",
	"Opening a passage between realms": "Membuka jalur antaralam",
	"A balanced foundation creates the strongest immortal path.": "Fondasi yang seimbang membentuk jalan keabadian terkuat.",
	"Equipment bonuses remain active throughout every cultivation run.": "Bonus perlengkapan tetap aktif sepanjang setiap sesi kultivasi.",
	"Flying swords answer faster when Swift Qi has been refined.": "Pedang terbang merespons lebih cepat setelah Swift Qi dimurnikan.",
	"Daily quests provide steady resources for patient cultivators.": "Disiplin harian memberi sumber daya stabil bagi kultivator yang tekun.",
	"True ascension is achieved through preparation, not haste.": "Keabadian sejati dicapai melalui persiapan, bukan tergesa-gesa.",
	"REALM": "ALAM",
	"No Chapters are available.": "Belum ada bab yang tersedia.",
	"Select an unlocked realm  •  Cleared progress is permanently recorded": "Pilih alam yang terbuka  •  Progres tuntas tercatat permanen",
	"Unavailable Realm": "Alam Tidak Tersedia",
	"No realm data": "Data alam tidak tersedia",
	"Unknown Realm": "Alam Tidak Dikenal",
	"CHAPTER %02d  •  %s": "BAB %02d  •  %s",
	"CLEARED %d/%d    UNLOCKED %d/%d": "TUNTAS %d/%d    TERBUKA %d/%d",
	"Chapter %d — %s\nCleared %d/%d • Unlocked %d/%d": "Bab %d — %s\nTuntas %d/%d • Terbuka %d/%d",
	"Unavailable": "Tidak Tersedia",
	"Trial data unavailable": "Data ujian tidak tersedia",
	"COMING SOON": "SEGERA HADIR",
	"BOSS GATE": "GERBANG PENJAGA",
	"BOSS • SOON": "PENJAGA • SEGERA",
	"SOON": "SEGERA",
	"Boss Gate": "Gerbang Penjaga",
	"Cultivation Trial": "Ujian Kultivasi",
	"REWARD READY": "HADIAH SIAP",
	"UNLOCKED": "TERBUKA",
	"MAX": "MAKS",
	"DAO CORE": "INTI DAO",
	"Equipment changes are sealed during an active run.": "Perubahan perlengkapan dikunci selama sesi aktif.",
	"UNEQUIP": "LEPAS",
	"Removing an item updates permanent loadout bonuses immediately.": "Melepas item langsung memperbarui bonus perlengkapan permanen.",
	"ITEM NOT OWNED": "ITEM BELUM DIMILIKI",
	"Acquire this equipment before it can be equipped.": "Dapatkan perlengkapan ini sebelum memasangnya.",
	"LOADOUT IMPACT  •  NO CHANGE — CURRENTLY EQUIPPED": "DAMPAK PERLENGKAPAN  •  TANPA PERUBAHAN — SEDANG TERPASANG",
	"LOADOUT IMPACT  •  EQUIP TO APPLY %s": "DAMPAK PERLENGKAPAN  •  PASANG UNTUK MENERAPKAN %s",
	"LOADOUT IMPACT  •  NO STAT CHANGE": "DAMPAK PERLENGKAPAN  •  STAT TIDAK BERUBAH",
	"LOADOUT IMPACT  •  %s": "DAMPAK PERLENGKAPAN  •  %s",
	"LOADOUT IMPACT  •  CHANGES THE SLOT'S STAT PROFILE": "DAMPAK PERLENGKAPAN  •  MENGUBAH PROFIL STAT SLOT",
	"STAT PROFILE CHANGE": "PERUBAHAN PROFIL STAT",
	"NO ACTIVE LOADOUT BONUSES": "TANPA BONUS PERLENGKAPAN AKTIF",
	"%s%.0f MAX HP": "%s%.0f HP MAKS",
	"%s%.0f%% DAMAGE": "%s%.0f%% KERUSAKAN",
	"%s%.0f%% MOVEMENT": "%s%.0f%% GERAK",
	"%s%.0f%% EXP": "%s%.0f%% EXP",
	"%s%.0f%% CRITICAL": "%s%.0f%% KRITIS",
	"PASSIVE EQUIPMENT": "PERLENGKAPAN PASIF",
	"MARTIAL RESONANCE": "RESONANSI BELA DIRI",
	"THIRD-PARTY NOTICES": "PEMBERITAHUAN PIHAK KETIGA",
	"ACTIVE TRIAL IN PROGRESS": "UJIAN AKTIF SEDANG BERJALAN",
	"ABANDON CURRENT TRIAL?": "TINGGALKAN UJIAN SAAT INI?",
	"Selected Trial": "Ujian Terpilih",
	"A saved run already exists. Starting this trial will replace that checkpoint.": "Sesi tersimpan masih ada. Memulai ujian ini akan mengganti checkpoint tersebut.",
	"PERMANENT PROGRESSION IS SAFE": "PROGRES PERMANEN TETAP AMAN",
	"KEEP SAVE": "PERTAHANKAN",
	"START NEW": "MULAI BARU",
	"LEVEL %d • BREAKTHROUGH": "LEVEL %d • TEROBOSAN",
	"WEAPON ART": "JURUS SENJATA",
	"BODY CULTIVATION": "KULTIVASI TUBUH",
	"DAO INSIGHT": "PEMAHAMAN DAO",
	"RESONANCE": "RESONANSI",
	"RESONANCE • UNLOCK": "RESONANSI • BUKA",
	"NEW ART": "JURUS BARU",
	"UPGRADE": "TINGKATKAN",
	"REFINE": "MURNIKAN",
	"MARTIAL FLOW": "ALIRAN BELA DIRI",
	"Power": "Daya",
	"Attack Speed": "Kecepatan Serangan",
	"Movement Speed": "Kecepatan Gerak",
	"Body Refinement": "Pemurnian Tubuh",
	"Spiritual Insight": "Pemahaman Spiritual",
	"Iron Body": "Tubuh Besi",
	"Refine the flying sword that hunts nearby enemies.": "Murnikan pedang terbang yang memburu musuh terdekat.",
	"Strengthen the fire orb launched toward nearby targets.": "Perkuat bola api yang melesat ke sasaran terdekat.",
	"Condense martial force to amplify all outgoing damage.": "Padatkan tenaga bela diri untuk memperkuat seluruh serangan.",
	"Cycle qi faster to shorten the interval between attacks.": "Alirkan Qi lebih cepat untuk memperpendek jeda serangan.",
	"Circulate swift qi through the body to move faster.": "Alirkan Qi lincah melalui tubuh agar bergerak lebih cepat.",
	"Temper the body to expand the vessel of life.": "Tempa tubuh untuk memperbesar daya hidup.",
	"Form a protective qi layer that negates an incoming hit.": "Bentuk lapisan Qi pelindung yang menahan satu serangan.",
	"Command chained lightning through a thunder talisman.": "Kendalikan petir berantai melalui jimat halilintar.",
	"Orbit paired blades around the cultivator to cut nearby foes.": "Putar sepasang bilah di sekeliling kultivator untuk menebas musuh.",
	"Call repeated sword strikes around a chosen enemy.": "Panggil hujan pedang berulang di sekitar musuh terpilih.",
	"Manifest a pulsing formation that damages enemies within it.": "Wujudkan formasi berdenyut yang melukai musuh di dalamnya.",
	"Deepen comprehension to gain more experience from battle.": "Perdalam pemahaman untuk memperoleh lebih banyak pengalaman.",
	"Harden flesh and bone to reduce incoming damage.": "Perkeras daging dan tulang untuk mengurangi luka.",
	"Convert repeated kills into gradual recovery during the run.": "Pulihkan HP secara bertahap dengan mengalahkan musuh.",
	"Sharpen sword intent to increase critical strike chance.": "Pertajam tekad pedang untuk meningkatkan peluang serangan kritis.",
	"Spirit Sword hits can launch a resonance sword toward a secondary enemy.": "Serangan Spirit Sword dapat meluncurkan pedang resonansi ke musuh kedua.",
	"A Qi Shield block awakens a temporary empowered Yin-Yang orbit.": "Blok Qi Shield memperkuat orbit Yin-Yang untuk sementara.",
	"Successful Sword Rain impacts can call down Heavenly Lightning.": "Hantaman Sword Rain dapat memanggil Heavenly Lightning.",
	"+5 BASE DAMAGE": "+5 KERUSAKAN DASAR",
	"+10 BASE DAMAGE": "+10 KERUSAKAN DASAR",
	"+10% DAMAGE POWER": "+10% DAYA SERANGAN",
	"ATTACK COOLDOWN ×0.90": "JEDA SERANGAN ×0,90",
	"MOVEMENT SPEED ×1.10": "KECEPATAN GERAK ×1,10",
	"+2 MAX HP • +2 HP": "+2 HP MAKS • +2 HP",
	"+1 SHIELD CHARGE": "+1 LAPIS PERISAI",
	"GAIN THUNDER TALISMAN": "PEROLEH THUNDER TALISMAN",
	"+4 BASE DAMAGE • CHAIN MILESTONES": "+4 KERUSAKAN DASAR • TAHAP RANTAI",
	"GAIN 2 ORBITING BLADES": "PEROLEH 2 BILAH BERPUTAR",
	"+3 BASE DAMAGE • BLADE MILESTONES": "+3 KERUSAKAN DASAR • TAHAP BILAH",
	"GAIN HEAVENLY SWORD RAIN": "PEROLEH HEAVENLY SWORD RAIN",
	"+4 BASE DAMAGE • STRIKE MILESTONES": "+4 KERUSAKAN DASAR • TAHAP HANTAMAN",
	"GAIN EIGHT TRIGRAMS FORMATION": "PEROLEH EIGHT TRIGRAMS FORMATION",
	"REFINE FORMATION BY LEVEL": "MURNIKAN FORMASI PER LEVEL",
	"+15% EXP MULTIPLIER": "+15% PENGALI EXP",
	"+5% DAMAGE REDUCTION": "+5% PENGURANGAN LUKA",
	"HEAL 1 HP • LOWER KILL THRESHOLD": "PULIHKAN 1 HP • KURANGI SYARAT KILL",
	"+5% CRITICAL CHANCE": "+5% PELUANG KRITIS",
	"SECONDARY SPIRIT SWORD": "SPIRIT SWORD TAMBAHAN",
	"4s EMPOWERED ORBIT AFTER SHIELD BLOCK": "ORBIT MENGUAT 4 DETIK SETELAH BLOK",
	"HEAVENLY LIGHTNING ON SWORD RAIN HIT": "HEAVENLY LIGHTNING SAAT SWORD RAIN MENGENAI",
	"RUN UPGRADE": "PENINGKATAN SESI",
	"RUN-LIMITED UNLOCK": "BERLAKU SELAMA SESI",
	"WAVE %d": "GELOMBANG %d",
	"PHASE %d": "FASE %d",
	"WAVE %d REACHED": "MENCAPAI GELOMBANG %d",
	"SPIRIT STONE BALANCE  •  %s": "SALDO BATU ROH  •  %s",
	"CONTINUE": "LANJUTKAN",
	"ENTER THE TRIAL": "MASUK KE UJIAN",
	"RESUME": "LANJUTKAN",
	"PAUSED": "JEDA",
	"RETURN HOME": "KEMBALI KE BERANDA",
	"RETRY": "COBA LAGI",
	"VICTORY": "KEMENANGAN",
	"DEFEAT": "KEKALAHAN",
	"Returning to Jade Sanctuary": "Kembali ke Pesanggrahan Giok",
	"Returning in Triumph": "Pulang Membawa Kemenangan",
	"Rekindling the Dao Heart": "Membangkitkan Hati Dao",
	"Defeat 20 enemies.": "Kalahkan 20 musuh.",
	"Defeat 50 enemies.": "Kalahkan 50 musuh.",
	"Defeat 100 enemies.": "Kalahkan 100 musuh.",
	"Defeat 250 enemies.": "Kalahkan 250 musuh.",
	"Defeat 1,000 enemies.": "Kalahkan 1.000 musuh.",
	"Reach Level 5 during a run.": "Capai Level 5 dalam satu sesi.",
	"Reach Level 7 during a run.": "Capai Level 7 dalam satu sesi.",
	"Reach Level 10 during a run.": "Capai Level 10 dalam satu sesi.",
	"Reach Level 20 during a run.": "Capai Level 20 dalam satu sesi.",
	"Clear 1 stage.": "Tuntaskan 1 ujian.",
	"Clear 2 stages, including repeats.": "Tuntaskan 2 ujian, termasuk pengulangan.",
	"Clear 3 stages, including repeats.": "Tuntaskan 3 ujian, termasuk pengulangan.",
	"Defeat your first enemy.": "Kalahkan musuh pertamamu.",
	"Clear your first stage.": "Tuntaskan ujian pertamamu.",
	"Defeat your first Stage Boss.": "Kalahkan penjaga ujian pertamamu.",
	"Purchase your first permanent cultivation upgrade.": "Beli peningkatan kultivasi permanen pertamamu.",
	"Clear all five Chapter 1 trials.": "Tuntaskan kelima ujian Bab 1.",
	"Defeat 10 stage guardians.": "Kalahkan 10 penjaga ujian.",
	"Own 10 permanent cultivation levels in total.": "Miliki total 10 level kultivasi permanen.",
	"Refine any combat art to Level 7.": "Murnikan satu jurus hingga Level 7.",
	"CONTINUE  •  C%d  S%d": "LANJUTKAN  •  B%d  U%d",
	"Chapter %d  •  Stage %d-%d": "Bab %d  •  Ujian %d-%d",
	"Stage %d-%d": "Ujian %d-%d",
	"Resuming Cultivation": "Melanjutkan Kultivasi",
	"Restoring the latest checkpoint": "Memulihkan checkpoint terakhir",
	"%d Spirit Stone": "%d Batu Roh",
	"No Reward": "Tanpa Hadiah",
	"No Reward Recovered": "Belum Ada Hadiah",
	"SAVE PENDING": "SIMPANAN TERTUNDA",
	"The Jade Sanctuary welcomes you": "Pesanggrahan Giok menyambutmu",
	"Returning to the battlefield": "Kembali ke medan pertempuran",
	"STAGE CLEAR": "UJIAN TUNTAS",
	"FLOWING STEPS": "LANGKAH MENGALIR",
	"Move Lin Yue to attune with the battlefield. Staying mobile is your first defense.": "Gerakkan Lin Yue untuk menguasai medan. Terus bergerak adalah pertahanan pertamamu.",
	"OBJECTIVE • MOVE TO CONTINUE": "TUJUAN • BERGERAK UNTUK MELANJUTKAN",
	"SELF-MOVING ARTS": "JURUS OTOMATIS",
	"Your equipped weapons strike automatically. Focus on positioning while Spirit Sword hunts nearby enemies.": "Senjatamu menyerang otomatis. Atur posisi sementara Spirit Sword memburu musuh terdekat.",
	"OBJECTIVE • DEFEAT 1 ENEMY": "TUJUAN • KALAHKAN 1 MUSUH",
	"ABSORB SPIRIT ESSENCE": "SERAP ESENSI ROH",
	"Collect essence from fallen enemies. Spirit essence fills EXP and drives your next breakthrough.": "Kumpulkan esensi dari musuh yang tumbang. Esensi mengisi EXP untuk terobosan berikutnya.",
	"OBJECTIVE • GAIN EXP": "TUJUAN • PEROLEH EXP",
	"BREAKTHROUGH": "TEROBOSAN",
	"When EXP is full, time seals itself. Choose one cultivation path to shape this run, then return to battle.": "Saat EXP penuh, waktu berhenti. Pilih satu peningkatan untuk sesi ini, lalu kembali bertempur.",
	"OBJECTIVE • REACH YOUR FIRST BREAKTHROUGH": "TUJUAN • CAPAI TEROBOSAN PERTAMA",
	"ASCENSION TRIAL": "UJIAN KEABADIAN",
	"Foundation forged. Survive the rising waves, refine your build, and defeat the stage guardian.": "Fondasi terbentuk. Bertahan menghadapi gelombang musuh, perkuat jurus, dan kalahkan penjaga ujian.",
	"DAO GUIDANCE COMPLETE": "BIMBINGAN DAO SELESAI",
	"DAO GUIDANCE  •  1 / 5": "BIMBINGAN DAO  •  1 / 5",
	"DAO GUIDANCE  •  2 / 5": "BIMBINGAN DAO  •  2 / 5",
	"DAO GUIDANCE  •  3 / 5": "BIMBINGAN DAO  •  3 / 5",
	"DAO GUIDANCE  •  4 / 5": "BIMBINGAN DAO  •  4 / 5",
	"DAO GUIDANCE  •  5 / 5": "BIMBINGAN DAO  •  5 / 5",
	"CREDITS & LICENSES": "KREDIT & LISENSI",
	"BACK": "KEMBALI",
	"Damage": "Kerusakan",
	"Movement": "Gerak",
	"Critical chance": "Peluang kritis",
	"Critical damage": "Kerusakan kritis",
	"Pickup radius": "Jangkauan serap",
	"Starting shield": "Perisai awal",
	"Blood Qi healing": "Pemulihan Blood Qi",
	"No stat bonus": "Tanpa bonus stat",
	"REFINEMENT MATERIAL": "BAHAN PEMURNIAN",
	"Use at Jade Pavilion to forge equipment.": "Gunakan di Paviliun Giok untuk menempa perlengkapan.",
	"Refinement Shard": "Pecahan Pemurnian",
	"OWNED %d UNIQUE  •  %d TOTAL": "DIMILIKI %d JENIS  •  %d TOTAL",
	"EQUIPPED %d / %d": "TERPASANG %d / %d",
	"EQUIPPED": "TERPASANG",
	"IN BACKPACK": "DI DALAM TAS",
	"LOADOUT READY  •  EQUIPMENT MAY BE REFINED": "PERLENGKAPAN SIAP  •  DAPAT DIGANTI",
	"LOADOUT SEALED  •  ACTIVE RUN CHECKPOINT": "PERLENGKAPAN TERKUNCI  •  SESI MASIH AKTIF",
	"LOADOUT SEALED": "PERLENGKAPAN TERKUNCI",
	"NOT OWNED": "BELUM DIMILIKI",
	"EQUIPPED  •  NONE": "TERPASANG  •  KOSONG",
	"EQUIPPED  •  %s  •  %s": "TERPASANG  •  %s  •  %s",
	"NO EQUIPMENT": "TANPA PERLENGKAPAN",
	"No equipment definition is available for this slot.": "Belum ada perlengkapan untuk slot ini.",
	"AWAKENED EFFECT  •  NONE": "EFEK BANGKIT  •  TIDAK ADA",
	"LOADOUT IMPACT  •  NONE": "PERUBAHAN STAT  •  TIDAK ADA",
	"NO ITEM AVAILABLE": "BELUM ADA ITEM",
	"CORE PASSIVE  •  %s  •  Owned x%d": "PASIF DASAR  •  %s  •  Dimiliki x%d",
	"Finish or clear the active run before changing equipment.": "Akhiri sesi aktif sebelum mengganti perlengkapan.",
	"NO AWAKENED EFFECT": "TANPA EFEK BANGKIT",
	"This equipment currently grants its core passive only.": "Perlengkapan ini memberikan pasif dasarnya saja.",
	"DEFENSIVE PASSIVE": "PASIF PERTAHANAN",
	"OFFENSIVE PASSIVE": "PASIF SERANGAN",
	"MOBILITY PASSIVE": "PASIF GERAK",
	"GROWTH PASSIVE": "PASIF PERTUMBUHAN",
	"BODY WARD": "PERLINDUNGAN TUBUH",
	"MARTIAL FORCE": "TENAGA BELA DIRI",
	"SPIRIT GROWTH": "PERTUMBUHAN ROH",
	"The reward could not be saved. Restart the game to recover.": "Hadiah belum tersimpan. Mulai ulang game untuk memulihkannya.",
	"Restart the game to recover a pending save.": "Mulai ulang game untuk memulihkan simpanan tertunda.",
	"Finish or abandon the current run before forging equipment.": "Selesaikan atau akhiri sesi aktif sebelum menempa perlengkapan.",
	"Insufficient Refinement Shards.": "Pecahan Pemurnian belum cukup.",
	"Insufficient Spirit Stones.": "Batu Roh belum cukup.",
	"The exchange could not be saved. Restart the game to recover.": "Penukaran belum tersimpan. Mulai ulang game untuk memulihkannya.",
	"Wandering Cultivator": "Kultivator Pengembara",
	"Shrinekeeper Aura": "Aura Penjaga Kuil",
	"Sovereign Aura": "Aura Penguasa",
	"An open valley of spirit grass and ancient cultivation markers.": "Lembah terbuka dengan rerumputan roh dan penanda kultivasi kuno.",
	"Valley disciples • Trial Guardian": "Murid lembah • Penjaga Ujian",
	"Mist curls between bamboo groves. Watch the flanks for shadowblades.": "Kabut menyelimuti rumpun bambu. Waspadai penyergap dari samping.",
	"Ranged ambushers • Mobile Mistblade Warden": "Penyergap jarak jauh • Mistblade Warden yang lincah",
	"Broken shrines awaken old wards. Leave the closing seal before it ignites.": "Reruntuhan kuil membangkitkan pelindung lama. Tinggalkan segel sebelum menyala.",
	"Ward keepers • Shrine seals • Jade Shrine Keeper": "Penjaga pelindung • Segel kuil • Jade Shrine Keeper",
	"Wind scours dark jade stone. Dodge marked lightning before the Herald arrives.": "Angin menyapu batu giok gelap. Hindari tanda petir sebelum sang Herald tiba.",
	"Storm Cultivators • Lightning • Stormpeak Herald": "Kultivator badai • Petir • Stormpeak Herald",
	"Cross the golden seals and face the Jade Valley Sovereign's awakened phase.": "Lintasi segel emas dan hadapi fase kebangkitan Jade Valley Sovereign.",
	"Mixed disciples • Celestial seals • Two-phase Sovereign": "Beragam murid • Segel langit • Dua fase Sovereign",
	"ALIGNING SPIRIT VEINS": "MENYELARASKAN NADI ROH",
	"OPENING CELESTIAL GATE": "MEMBUKA GERBANG LANGIT",
	"STABILIZING PASSAGE": "MENSTABILKAN JALUR",
	"PASSAGE STABLE": "JALUR SIAP",
	"Awakening the immortal path": "Membangkitkan jalan keabadian",
	"Every ascendant begins with a single breath of Qi.": "Setiap jalan keabadian dimulai dari satu tarikan Qi.",
	"TRAVERSING THE CELESTIAL PATH": "MELINTASI JALAN LANGIT",
	"DAILY CYCLE  •  ": "SIKLUS HARIAN  •  ",
	"  •  DAILY DISCIPLINE": "  •  DISIPLIN HARIAN",
	"  •  PERMANENT RECORD": "  •  CATATAN PERMANEN",
	"combat": "pertempuran",
	"progression": "progres",
	"journey": "perjalanan",
	"cultivation": "kultivasi",
	"boss": "penjaga",
	"CULTIVATION TRIAL": "UJIAN KULTIVASI",
	"CHAPTER BOSS": "PENJAGA BAB",
	"READY": "SIAP",
	"COMPLETE PRIOR TRIAL": "TUNTASKAN UJIAN SEBELUMNYA",
	"CLEARED • REPLAY AVAILABLE": "TUNTAS • DAPAT DIULANG",
	"First clear": "Pertama tuntas",
	"Replay reward": "Hadiah pengulangan",
	"Open Lin Yue profile": "Buka profil Lin Yue",
	"PERMANENT COMBAT PROFILE": "PROFIL TEMPUR PERMANEN",
	"Permanent stats • before run-only upgrades": "Stat permanen • sebelum peningkatan khusus sesi",
	"NEXT RUN PROFILE": "PROFIL SESI BERIKUTNYA",
	"Continue keeps the loadout saved with the active checkpoint.": "Lanjutkan memakai perlengkapan yang tersimpan pada checkpoint aktif.",
	"CORE STATS": "STAT UTAMA",
	"MAX HP BONUS": "BONUS HP MAKS",
	"DAMAGE BONUS": "BONUS KERUSAKAN",
	"ATTACK SPEED": "KECEPATAN SERANGAN",
	"MOVEMENT SPEED": "KECEPATAN GERAK",
	"EXP GAIN": "PEROLEHAN EXP",
	"CRITICAL CHANCE": "PELUANG KRITIS",
	"CRITICAL DAMAGE": "KERUSAKAN KRITIS",
	"Vitality and permanent equipment.": "Vitality dan perlengkapan permanen.",
	"Always-on damage before run upgrades.": "Bonus kerusakan yang selalu aktif sebelum peningkatan sesi.",
	"Swift Qi and permanent cooldown effects.": "Swift Qi dan efek cooldown permanen.",
	"Permanent movement bonus from equipment.": "Bonus gerak permanen dari perlengkapan.",
	"Permanent bonus to Qi shard experience.": "Bonus permanen EXP dari pecahan Qi.",
	"Permanent critical chance before Sword Intent.": "Peluang kritis permanen sebelum Sword Intent.",
	"Damage dealt by a critical hit.": "Besarnya kerusakan saat serangan kritis terjadi.",
	"SIGNATURE EFFECTS": "EFEK KHAS",
	"COOLDOWN REDUCTION": "PENGURANGAN COOLDOWN",
	"PICKUP RADIUS": "JANGKAUAN PICKUP",
	"STARTING QI SHIELD": "QI SHIELD AWAL",
	"LEVEL-UP RECOVERY": "PEMULIHAN SAAT NAIK LEVEL",
	"BLOOD QI RECOVERY": "PEMULIHAN BLOOD QI",
	"MOVING DAMAGE": "KERUSAKAN SAAT BERGERAK",
	"LOW-HP DAMAGE": "KERUSAKAN HP RENDAH",
	"LOW-HP CRITICAL": "KRITIS HP RENDAH",
	"Reduces weapon-art cooldown time.": "Mengurangi waktu cooldown jurus senjata.",
	"Qi shards begin following Lin Yue from farther away.": "Pecahan Qi mulai mengikuti Lin Yue dari jarak lebih jauh.",
	"Fresh runs begin with this many shield charges.": "Sesi baru dimulai dengan jumlah charge pelindung ini.",
	"Healing received whenever run level increases.": "Pemulihan HP setiap level sesi meningkat.",
	"Additional healing when Blood Qi triggers.": "Tambahan pemulihan saat Blood Qi terpicu.",
	"Conditional bonus while Lin Yue is moving.": "Bonus kondisional saat Lin Yue bergerak.",
	"Conditional bonus at or below 50% HP.": "Bonus kondisional saat HP 50% atau kurang.",
	"Extra critical chance at or below 50% HP.": "Tambahan peluang kritis saat HP 50% atau kurang.",
	"VITALITY": "VITALITY",
	"SWORD POWER": "SWORD POWER",
	"SWIFT QI": "SWIFT QI",
	"Raises permanent Max HP.": "Meningkatkan HP Maks permanen.",
	"Raises permanent outgoing damage.": "Meningkatkan kerusakan permanen.",
	"Shortens base weapon-art cooldowns.": "Memperpendek cooldown dasar jurus senjata.",
	"NEXT RUN LOADOUT": "PERLENGKAPAN SESI BERIKUTNYA",
	"EMPTY": "KOSONG",
	"ARMAMENT": "SENJATA DAO",
	"HERO MILESTONES": "TAHAP HERO",
	"NEXT MILESTONE  •  LV %d": "TAHAP BERIKUT  •  LV %d",
	"MILESTONE READY  •  LV %d": "TAHAP SIAP  •  LV %d",
	"CLAIM MILESTONE REWARD  •  LV %d": "KLAIM HADIAH TAHAP  •  LV %d",
	"ALL HERO MILESTONES CLAIMED": "SEMUA HADIAH TAHAP HERO SUDAH DIKLAIM",
	"ALL HERO MILESTONES REACHED": "SEMUA TAHAP HERO TERCAPAI",
	"RUN-ONLY STATS EXCLUDED": "STAT KHUSUS SESI TIDAK DITAMPILKAN",
	"Power, Sword Intent, Body Refinement and other breakthrough upgrades reset each run.": "Power, Sword Intent, Body Refinement, dan peningkatan breakthrough lainnya direset setiap sesi.",

	"Balanced survival • healing • mobility": "Bertahan seimbang • pemulihan • mobilitas",
	"Mobile tempo • cooldown • moving damage": "Tempo bergerak • cooldown • kerusakan saat bergerak",
	"Growth • critical precision • recovery": "Pertumbuhan • presisi kritis • pemulihan",
	"Low-HP aggression • critical damage": "Agresi HP rendah • kerusakan kritis",
	"Endgame tempo • damage • critical precision": "Tempo endgame • kerusakan • presisi kritis",
	"Defense • shield • sustain": "Pertahanan • pelindung • daya tahan",
	"Stationary precision • critical burst": "Presisi diam • ledakan kritis",
	"High-HP mastery • offense • tempo": "Penguasaan HP tinggi • serangan • tempo",
	"+4 Max HP": "+4 HP Maks",
	"+2% Movement": "+2% Gerak",
	"+0.10 Blood Qi healing": "+0.10 Pemulihan Blood Qi",
	"+0.75 Level-up healing": "+0.75 Pemulihan saat naik level",
	"-2% Weapon-art cooldown": "-2% Cooldown jurus senjata",
	"+2% Damage while moving": "+2% Kerusakan saat bergerak",
	"+1% Movement • -1% Weapon-art cooldown": "+1% Gerak • -1% Cooldown jurus senjata",
	"+2.5% EXP": "+2.5% EXP",
	"+1% Critical chance": "+1% Peluang kritis",
	"+0.5 Level-up healing": "+0.5 Pemulihan saat naik level",
	"+1.5% EXP • +0.5% Critical chance": "+1.5% EXP • +0.5% Peluang kritis",
	"+1.5% Damage": "+1.5% Kerusakan",
	"+3% Damage at ≤50% HP": "+3% Kerusakan saat HP ≤50%",
	"+1.5% Critical chance at ≤50% HP": "+1.5% Peluang kritis saat HP ≤50%",
	"+6% Critical damage": "+6% Kerusakan kritis",
	"+1% Damage": "+1% Kerusakan",
	"-1.5% Weapon-art cooldown": "-1.5% Cooldown jurus senjata",
	"+0.75% Critical chance": "+0.75% Peluang kritis",
	"+2% EXP": "+2% EXP",
	"+5 Max HP": "+5 HP Maks",
	"+1 Starting Qi Shield": "+1 Qi Shield awal",
	"+4% Damage while stationary": "+4% Kerusakan saat diam",
	"+5% Critical damage": "+5% Kerusakan kritis",
	"+4% Damage at ≥80% HP": "+4% Kerusakan saat HP ≥80%",

	"CELESTIAL SUMMON": "PANGGILAN LANGIT",
	"THE ARMORY STIRS": "GUDANG SENJATA BERGEMA",
	"SEALED RELIC": "RELIK TERSEGEL",
	"CELESTIAL SEAL": "SEGEL LANGIT",

	"SEALED ARMAMENT": "SENJATA TERSEGEL",
	"SEALED ROBE": "JUBAH TERSEGEL",
	"SEALED BRACER": "PELINDUNG LENGAN TERSEGEL",
	"SEALED BOOTS": "SEPATU TERSEGEL",
	"SEALED PENDANT": "LIONTIN TERSEGEL",
	"A WEAPON SPIRIT WAITS WITHIN": "ROH SENJATA MENUNGGU DI DALAM",
	"A PROTECTIVE GARMENT WAITS WITHIN": "JUBAH PELINDUNG MENUNGGU DI DALAM",
	"A MARTIAL RELIC WAITS WITHIN": "RELIK BELADIRI MENUNGGU DI DALAM",
	"A SWIFT FOOTWORK RELIC WAITS WITHIN": "RELIK LANGKAH CEPAT MENUNGGU DI DALAM",
	"A SPIRIT TALISMAN WAITS WITHIN": "JIMAT ROH MENUNGGU DI DALAM",
	"REVEAL THE EQUIPMENT WITHIN": "UNGKAP PERLENGKAPAN DI DALAMNYA",
	"READY TO REVEAL": "SIAP DIUNGKAP",
	"SKIP TO RESULTS": "LEWATI KE HASIL",
	"REVEAL": "UNGKAP",
	"PULL %d OF %d": "PANGGILAN %d DARI %d",
	"SET • %s": "SET • %s",
	"SIGNATURE • %s": "EFEK KHAS • %s",
	"DUPLICATE TRANSMUTED • +%d SHARDS": "DUPLIKAT DITRANSMUTASI • +%d PECAHAN",
	"NEW DISCOVERY • ADDED TO COLLECTION": "TEMUAN BARU • DITAMBAHKAN KE KOLEKSI",
	"VIEW SUMMON RESULTS": "LIHAT HASIL PANGGILAN",
	"NEXT REVEAL • %d/%d": "UNGKAP BERIKUT • %d/%d",
	"COLLECTION • %d / %d": "KOLEKSI • %d / %d",
	"HEAVENLY RELIC INVOCATION": "PEMANGGILAN RELIK LANGIT",
	"FATE CONSTELLATION": "KONSTELASI TAKDIR",
	"AWAITING HEAVENLY SIGN": "MENANTI PERTANDA LANGIT",
	"CELESTIAL OMEN": "PERTANDA LANGIT",
	"JADE QI GATHERS": "QI GIOK BERKUMPUL",
	"AZURE STARS ANSWER": "BINTANG AZURE MENJAWAB",
	"PURPLE HEAVENS RESONATE": "LANGIT UNGU BERESONANSI",
	"THE HEAVENS TURN GOLD": "LANGIT BERUBAH EMAS",
	"THE CELESTIAL ARRAY IS ANSWERING": "FORMASI LANGIT SEDANG MENJAWAB",
	"FATE IS BEING READ": "TAKDIR SEDANG DIBACA",
	"CELESTIAL RELIC REVEALED": "RELIK LANGIT TERUNGKAP",
	"HEAVENLY RELIC DESCENDS": "RELIK LANGIT TURUN",

	# Hero / Equipment Collection presentation coverage.
	"ACTIVE": "AKTIF",
	"ASCENSION  •  NO ITEM": "ASCENSION  •  TANPA ITEM",
	"Acquire this equipment to unlock ascension.": "Dapatkan perlengkapan ini untuk membuka ascension.",
	"Applies to the next journey and saves permanently.": "Berlaku untuk perjalanan berikutnya dan disimpan permanen.",
	"Ascension saves for NEXT RUN; Continue keeps the checkpoint stars.": "Ascension disimpan untuk SESI BERIKUTNYA; Lanjutkan tetap memakai bintang checkpoint.",
	"CELESTIAL LIMIT REACHED\nCore passive +20% from 1★": "BATAS LANGIT TERCAPAI\nPasif inti +20% dari 1★",
	"COLLECTION COMPLETE": "KOLEKSI LENGKAP",
	"COMPARISON  •  %s": "PERBANDINGAN  •  %s",
	"COMPARISON  •  NO STAT CHANGE": "PERBANDINGAN  •  TIDAK ADA PERUBAHAN STAT",
	"CORE PASSIVE UNCHANGED": "PASIF INTI TIDAK BERUBAH",
	"CURRENT LOADOUT  •  EQUIPPED": "LOADOUT SAAT INI  •  TERPASANG",
	"Core passive increases. Signature Effect remains unchanged.": "Pasif inti meningkat. Efek Khas tetap sama.",
	"Core passives scale with stars; Signature Effects stay fixed.": "Pasif inti meningkat bersama bintang; Efek Khas tetap.",
	"Equip matching set pieces to awaken resonance.": "Pasang bagian set yang cocok untuk membangkitkan resonansi.",
	"JADE LOADOUT": "LOADOUT GIOK",
	"LOADOUT RESONANCE": "RESONANSI LOADOUT",
	"SHOWING %d": "MENAMPILKAN %d",
	"LOADOUT LOCKED": "LOADOUT TERKUNCI",
	"LOADOUT LOCKED  •  SAVE RECOVERY REQUIRED": "LOADOUT TERKUNCI  •  PEMULIHAN SAVE DIPERLUKAN",
	"MISSING": "BELUM DIMILIKI",
	"NEXT CORE PASSIVE\n%s": "PASIF INTI BERIKUT\n%s",
	"NEXT RUN LOADOUT  •  CONTINUE KEEPS SAVED LOADOUT": "LOADOUT SESI BERIKUTNYA  •  LANJUTKAN TETAP MEMAKAI LOADOUT TERSIMPAN",
	"NO ASCENSION DATA": "TIDAK ADA DATA ASCENSION",
	"NO EQUIPMENT FOUND": "PERLENGKAPAN TIDAK DITEMUKAN",
	"NO OWNED EQUIPMENT YET": "BELUM ADA PERLENGKAPAN YANG DIMILIKI",
	"No equipment set is currently attuned.": "Belum ada set perlengkapan yang sedang selaras.",
	"None": "Tidak ada",
	"Resolve save recovery before ascending equipment.": "Selesaikan pemulihan save sebelum melakukan ascension perlengkapan.",
	"Resolve save recovery before changing equipment.": "Selesaikan pemulihan save sebelum mengganti perlengkapan.",
	"SIGNATURE": "EFEK KHAS",
	"SIGNATURE EFFECT\nNone": "EFEK KHAS\nTidak ada",
	"Saved for NEXT RUN. Continue keeps the checkpoint loadout.": "Disimpan untuk SESI BERIKUTNYA. Lanjutkan tetap memakai loadout checkpoint.",
	"This relic has reached 5★ resonance.": "Relik ini telah mencapai resonansi 5★.",

}

func _enter_tree() -> void:
	var translation: Translation = Translation.new()
	translation.locale = "id"
	for message in INDONESIAN:
		translation.add_message(str(message), str(INDONESIAN[message]))
	TranslationServer.add_translation(translation)
