extends Node

## English message IDs; proper names of arts, items and realms stay consistent.
const INDONESIAN: Dictionary = {
	"SAVE FAILED • TRY AGAIN": "GAGAL MENYIMPAN • COBA LAGI",
	"Your run is still open. Free device storage or retry saving before leaving.": "Sesi masih terbuka. Kosongkan penyimpanan perangkat atau coba simpan lagi sebelum keluar.",
	"HOME": "BERANDA",
	"CULTIVATE": "KULTIVASI",
	"HERO": "HERO",
	"TRIALS": "UJIAN",
	"PAVILION": "PAVILIUN",
	"JADE SANCTUARY": "PESANGGRAHAN GIOK",
	"Your path to ascension": "Jalanmu menuju keabadian",
	"CONTINUE RUN": "LANJUTKAN",
	"ENTER JOURNEY": "MULAI PERJALANAN",
	"DAILY TRIALS": "UJIAN HARIAN",
	"ACHIEVEMENTS": "PENCAPAIAN",
	"%d / %d trials cleared  •  Your path to ascension": "%d / %d ujian tuntas  •  Jalan menuju keabadian",
	"CHAPTER COMPLETE  •  Revisit any trial in Journey": "BAB TUNTAS  •  Ulangi ujian melalui Perjalanan",
	"CONTINUE  •  %s": "LANJUTKAN  •  %s",
	"CONTINUE  •  STAGE %d-%d": "LANJUTKAN  •  UJIAN %d-%d",
	"‹  HOME": "‹  BERANDA",
	"‹   BACK": "‹   KEMBALI",
	"PREFERENCES": "PREFERENSI",
	"Settings": "Pengaturan",
	"Audio mixing • saved automatically on this device": "Volume • tersimpan otomatis di perangkat",
	"AUDIO MIXER": "PENGATURAN AUDIO",
	"Spiritual Resonance": "Resonansi Spiritual",
	"MUSIC & SOUND": "MUSIK & SUARA",
	"Master Volume": "Volume Utama",
	"Controls the final output of every audio channel.": "Mengatur volume seluruh suara.",
	"Music": "Musik",
	"Controls music routed through the Music channel.": "Mengatur volume musik latar.",
	"Sound Effects": "Efek Suara",
	"Controls combat, interface, and world effects routed to SFX.": "Mengatur suara pertempuran, tombol, dan lingkungan.",
	"Applied instantly • saved automatically on this device.": "Langsung diterapkan • tersimpan otomatis di perangkat.",
	"RESTORE AUDIO DEFAULTS": "PULIHKAN VOLUME AWAL",
	"COMFORT & LANGUAGE": "KENYAMANAN & BAHASA",
	"Screen shake": "Guncangan layar",
	"Reduced flashes and effects": "Kurangi kilatan dan efek",
	"Damage numbers": "Angka kerusakan",
	"Vibration": "Getaran",
	"60 FPS • Smooth": "60 FPS • Gerakan halus",
	"30 FPS • Battery saver": "30 FPS • Hemat baterai",
	"Sound is temporarily unavailable.": "Suara sementara tidak tersedia.",
	"PRIVACY & SUPPORT": "PRIVASI & BANTUAN",
	"Your journey stays on your device.": "Perjalananmu tersimpan di perangkatmu.",
	"This offline edition does not send gameplay data, personal information, or device identifiers to a server. It has no account, advertising, analytics service, or real-money purchases.": "Edisi luring ini tidak mengirim data permainan, informasi pribadi, atau pengenal perangkat ke server. Tidak ada akun, iklan, layanan analitik, atau pembelian dengan uang nyata.",
	"What the game saves": "Data yang disimpan",
	"Progress, equipment, achievements, daily trials, run checkpoints, and preferences are stored locally. Daily trials and meditation use your device date. Auras change appearance only.": "Progres, perlengkapan, pencapaian, ujian harian, checkpoint, dan preferensi disimpan secara lokal. Ujian harian dan meditasi memakai tanggal perangkat. Aura hanya mengubah penampilan.",
	"Deleting your data": "Menghapus data",
	"On Android, use Settings > Apps > Jade Ascendant > Storage > Clear storage, or uninstall the game. This removes local progress. This edition has no cloud save or account recovery.": "Di Android, buka Pengaturan > Aplikasi > Jade Ascendant > Penyimpanan > Hapus data, atau copot game. Progres lokal akan terhapus. Edisi ini tidak memiliki simpanan awan atau pemulihan akun.",
	"Optional vibration": "Getaran opsional",
	"Vibration can be enabled in Settings. It only provides feedback during combat and does not collect data.": "Getaran dapat diaktifkan di Pengaturan. Fungsinya memberi respons saat bertempur dan tidak mengumpulkan data.",
	"External links and support": "Tautan luar dan bantuan",
	"Opening the policy or support link uses an external browser or email app. Information you choose to send for support is handled by the publisher under the published privacy policy.": "Tautan kebijakan atau bantuan membuka peramban atau aplikasi surel. Informasi yang kamu kirim untuk bantuan ditangani penerbit sesuai kebijakan privasi yang diterbitkan.",
	"OPEN PRIVACY POLICY": "BUKA KEBIJAKAN PRIVASI",
	"CONTACT SUPPORT": "HUBUNGI BANTUAN",
	"BACK TO SETTINGS": "KEMBALI KE PENGATURAN",
	"JADE PAVILION": "PAVILIUN GIOK",
	"Rest, gather your Qi, and prepare for the next trial.": "Beristirahat, himpun Qi, dan bersiap menghadapi ujian berikutnya.",
	"Daily Meditation": "Meditasi Harian",
	"A quiet moment grants 20 Spirit Stones once per local day.": "Meditasi memberikan 20 Batu Roh sekali sehari menurut tanggal perangkat.",
	"MEDITATE  •  +20 SPIRIT STONES": "MEDITASI  •  +20 BATU ROH",
	"MEDITATED TODAY": "SUDAH MEDITASI HARI INI",
	"Cultivation Auras": "Aura Kultivasi",
	"Complete trials to unlock auras. These change appearance only.": "Tuntaskan ujian untuk membuka aura. Aura hanya mengubah penampilan.",
	"Equipment Forge": "Penempaan Perlengkapan",
	"Exchange earned Spirit Stones or Refinement Shards for equipment. Duplicate rewards become shards automatically.": "Tukar Batu Roh atau Pecahan Pemurnian hasil bermain dengan perlengkapan. Hadiah duplikat otomatis menjadi pecahan.",
	"About Jade Ascendant": "Tentang Jade Ascendant",
	"This edition plays offline. All equipment is earned through play. No ads or real-money purchases are included.": "Edisi ini dimainkan luring. Semua perlengkapan diperoleh melalui permainan. Tidak ada iklan atau pembelian dengan uang nyata.",
	"%d Spirit Stones  •  %d Refinement Shards": "%d Batu Roh  •  %d Pecahan Pemurnian",
	"  •  Clear 1-%d": "  •  Tuntaskan 1-%d",
	"A save needs recovery. Close and reopen the game before continuing.": "Simpanan perlu dipulihkan. Tutup dan buka kembali game sebelum melanjutkan.",
	"Finish the current run to use the forge.": "Selesaikan sesi yang berjalan untuk memakai penempaan.",
	"OWNED  •  Equip from Hero": "DIMILIKI  •  Pasang melalui Hero",
	"Unlock after clearing trial 1-%d": "Terbuka setelah menuntaskan ujian 1-%d",
	"EXCHANGE  •  %d SPIRIT STONES": "TUKAR  •  %d BATU ROH",
	"FORGE  •  %d REFINEMENT SHARDS": "TEMPA  •  %d PECAHAN PEMURNIAN",
	"Meditation complete. +20 Spirit Stones.": "Meditasi selesai. +20 Batu Roh.",
	"Aura selected.": "Aura dipilih.",
	"Equipment acquired. Open Hero to equip it.": "Perlengkapan diperoleh. Buka Hero untuk memasangnya.",
	"Common": "Umum",
	"Rare": "Langka",
	"Epic": "Epik",
	"Legendary": "Legendaris",
	"damage": "kerusakan",
	"speed": "kecepatan",
	"critical chance": "peluang kritis",
	"Plain Robes": "Tanpa Aura",
	"Jade Aura": "Aura Giok",
	"Golden Aura": "Aura Emas",
	"JOURNEY   •   REALMS": "PERJALANAN   •   ALAM",
	"CELESTIAL JOURNEY": "PERJALANAN LANGIT",
	"SELECT CHAPTER": "PILIH BAB",
	"VALLEY OF AWAKENING": "LEMBAH KEBANGKITAN",
	"Choose a cultivation realm and continue the path toward ascension.": "Pilih alam kultivasi dan lanjutkan perjalanan menuju keabadian.",
	"AVAILABLE REALMS": "ALAM TERSEDIA",
	"ASCENSION PATH": "JALAN KEABADIAN",
	"Unlocked realms can be revisited. Cleared progress is permanent.": "Alam yang terbuka dapat diulang. Progres penyelesaian bersifat permanen.",
	"JOURNEY   •   TRIALS": "PERJALANAN   •   UJIAN",
	"CHAPTER": "BAB",
	"CHAPTER %02d": "BAB %02d",
	"CULTIVATION REALM": "ALAM KULTIVASI",
	"SELECT A TRIAL AND CONTINUE YOUR ASCENSION": "PILIH UJIAN DAN LANJUTKAN JALAN KEABADIAN",
	"REALM TRIALS": "UJIAN ALAM",
	"PROGRESS IS PERMANENT": "PROGRES BERSIFAT PERMANEN",
	"SELECTED TRIAL": "UJIAN TERPILIH",
	"No playable stage selected": "Belum ada ujian yang dipilih",
	"BEGIN TRIAL": "MULAI UJIAN",
	"SELECTED": "TERPILIH",
	"CLEARED": "TUNTAS",
	"AVAILABLE": "TERSEDIA",
	"LOCKED": "TERKUNCI",
	"UNAVAILABLE": "TIDAK TERSEDIA",
	"FIRST CLEAR": "PENYELESAIAN PERTAMA",
	"REPEAT CLEAR": "PENYELESAIAN ULANG",
	"First Clear Reward": "Hadiah Penyelesaian Pertama",
	"Repeat Clear Reward": "Hadiah Penyelesaian Ulang",
	"Stage Clear Reward": "Hadiah Ujian",
	"Boss Reward": "Hadiah Penjaga",
	"FIRST CLEAR • PROGRESS RECORDED": "PERTAMA TUNTAS • PROGRES TERSIMPAN",
	"REPEAT CLEAR • REWARD SECURED": "ULANG TUNTAS • HADIAH TERSIMPAN",
	"STAGE CLEAR • REWARD SECURED": "UJIAN TUNTAS • HADIAH TERSIMPAN",
	"TRIAL HALL  •  DAILY DISCIPLINES": "BALAI UJIAN  •  DISIPLIN HARIAN",
	"JADE TRIAL HALL • CULTIVATION RECORDS": "BALAI UJIAN GIOK • CATATAN KULTIVASI",
	"Daily Trials": "Ujian Harian",
	"DAILY CYCLE": "SIKLUS HARIAN",
	"DAILY": "HARIAN",
	"COMPLETED": "SELESAI",
	"REWARDS READY": "HADIAH SIAP",
	"NO REWARDS": "BELUM ADA HADIAH",
	"DAILY CYCLE PROGRESS": "PROGRES SIKLUS HARIAN",
	"%d / %d COMPLETE": "%d / %d SELESAI",
	"Complete every daily discipline to finish today's trial cycle.": "Selesaikan seluruh disiplin harian untuk menuntaskan siklus hari ini.",
	"TRIAL HALL  •  ETERNAL RECORDS": "BALAI UJIAN  •  CATATAN ABADI",
	"Achievement Records": "Catatan Pencapaian",
	"ETERNAL RECORDS": "CATATAN ABADI",
	"ETERNAL RECORDS  •  %d DISCOVERED": "CATATAN ABADI  •  %d TERBUKA",
	"DISCOVERED": "TERBUKA",
	"REWARD  •  %d SPIRIT STONE": "HADIAH  •  %d BATU ROH",
	"CLAIMED": "DIAMBIL",
	"CLAIM REWARD": "AMBIL HADIAH",
	"CLAIM ALL": "AMBIL SEMUA",
	"CLAIM ALL (%d)": "AMBIL SEMUA (%d)",
	"IN PROGRESS": "BERLANGSUNG",
	"CULTIVATION": "KULTIVASI",
	"SACRED MERIDIAN FORMATION": "FORMASI MERIDIAN SUCI",
	"INNER SEA  •  PERMANENT CULTIVATION": "LAUTAN BATIN  •  KULTIVASI PERMANEN",
	"Sacred Cultivation Formation": "Formasi Kultivasi Suci",
	"MERIDIAN MASTERY %d / %d": "PENGUASAAN MERIDIAN %d / %d",
	"BODY MERIDIAN": "MERIDIAN TUBUH",
	"Vitality": "Vitalitas",
	"Strengthen the body and expand the vessel of qi.": "Perkuat tubuh dan perluas wadah Qi.",
	"Refine sword intent into permanent spiritual power.": "Murnikan tekad pedang menjadi kekuatan spiritual permanen.",
	"CURRENT EFFECT": "EFEK SAAT INI",
	"NEXT REFINEMENT": "PEMURNIAN BERIKUTNYA",
	"LEVEL %d / %d": "LEVEL %d / %d",
	"REFINE MERIDIAN": "MURNIKAN MERIDIAN",
	"MERIDIAN PERFECTED": "MERIDIAN SEMPURNA",
	"This meridian has reached its current limit.": "Meridian ini telah mencapai batasnya.",
	"Need %d more Spirit Stones.": "Perlu %d Batu Roh lagi.",
	"Permanent upgrade • persists between journeys.": "Peningkatan permanen • tetap ada antarperjalanan.",
	"+%d MAX HP": "+%d HP MAKS",
	"+%d%% POWER": "+%d%% DAYA",
	"%.3f ATTACKS/S": "%.3f SERANGAN/DETIK",
	"PERFECTED": "SEMPURNA",
	"MARTIAL LOADOUT  •  JADE PAVILION": "PERLENGKAPAN BELA DIRI  •  PAVILIUN GIOK",
	"WANDERING CULTIVATOR  •  MARTIAL RESONANCE": "KULTIVATOR PENGEMBARA  •  RESONANSI BELA DIRI",
	"WANDERING CULTIVATOR": "KULTIVATOR PENGEMBARA",
	"EQUIPPED %d / 4": "TERPASANG %d / 4",
	"LOADOUT READY": "PERLENGKAPAN SIAP",
	"EQUIPMENT": "PERLENGKAPAN",
	"BACKPACK": "TAS",
	"EQUIPPED GEAR": "PERLENGKAPAN TERPASANG",
	"ARMAMENT": "SENJATA DAO",
	"ROBE": "JUBAH",
	"BRACER": "PELINDUNG LENGAN",
	"PENDANT": "LIONTIN",
	"BOOTS": "SEPATU",
	"EMPTY SLOT": "SLOT KOSONG",
	"EQUIP ITEM": "PASANG",
	"UNEQUIP ITEM": "LEPAS",
	"AVAILABLE EQUIPMENT FOR THIS SLOT": "PERLENGKAPAN UNTUK SLOT INI",
	"Equipment changes are saved permanently outside active runs.": "Perubahan perlengkapan tersimpan permanen di luar sesi aktif.",
	"BACKPACK  •  EQUIPMENT INVENTORY": "TAS  •  INVENTARIS PERLENGKAPAN",
	"LOADOUT": "PERLENGKAPAN",
	"MY EQUIPMENT  •  TAP AN ITEM FOR DETAILS": "PERLENGKAPAN SAYA  •  KETUK ITEM UNTUK DETAIL",
	"INVENTORY  •  TAP AN ITEM FOR DETAILS": "INVENTARIS  •  KETUK ITEM UNTUK DETAIL",
	"ALL": "SEMUA",
	"GEAR": "PAKAI",
	"MATERIAL": "BAHAN",
	"SORT  •  %s": "URUT  •  %s",
	"SORT  •  RARITY": "URUT  •  RARITAS",
	"EQUIP %s": "PASANG %s",
	"CLOUDSTEP": "LANGKAH AWAN",
	"SLOT": "SLOT",
	"NAME": "NAMA",
	"NO ITEM SELECTED": "BELUM ADA ITEM DIPILIH",
	"Choose an item from the backpack grid.": "Pilih item dari grid tas.",
	"NO ACTION": "TIDAK ADA AKSI",
	"Tap × to return to the inventory grid.": "Ketuk × untuk kembali ke grid inventaris.",
	"Tap × to return to the equipment grid.": "Ketuk × untuk kembali ke grid perlengkapan.",
	"LOADOUT READY  •  SELECT A SLOT TO ATTUNE": "PERLENGKAPAN SIAP  •  PILIH SLOT",
	"Remove this item from the permanent loadout.": "Lepas item ini dari perlengkapan permanen.",
	"Inspect it here; forge or acquire it before equipping.": "Periksa item ini; tempa atau dapatkan sebelum memasangnya.",
	"Applies immediately and saves outside active runs.": "Langsung diterapkan dan tersimpan di luar sesi aktif.",
	"REFINEMENT MATERIAL  •  OWNED x%d": "BAHAN PEMURNIAN  •  DIMILIKI x%d",
	"PAVILION RESOURCE": "SUMBER DAYA PAVILIUN",
	"OPEN JADE PAVILION": "BUKA PAVILIUN GIOK",
	"Use Refinement Shards to forge unlocked equipment.": "Gunakan Pecahan Pemurnian untuk menempa perlengkapan yang terbuka.",
	"Equip directly without leaving the backpack.": "Pasang langsung tanpa meninggalkan tas.",
	"COMMON": "UMUM",
	"RARE": "LANGKA",
	"EPIC": "EPIK",
	"LEGENDARY": "LEGENDARIS",
	"Martial Backpack": "Tas Bela Diri",
	"OWNED EQUIPMENT": "PERLENGKAPAN DIMILIKI",
	"Your martial backpack is empty.": "Tas bela dirimu masih kosong.",
	"SKIP": "LEWATI",
	"SPIRITUAL BREAKTHROUGH • RUN CULTIVATION": "TEROBOSAN SPIRITUAL • KULTIVASI SESI",
	"CHOOSE YOUR PATH": "PILIH JALURMU",
	"One insight will shape the rest of this run.": "Satu pemahaman akan membentuk sisa sesi ini.",
	"Choose one path. The battlefield resumes immediately after selection.": "Pilih satu jalur. Pertempuran langsung berlanjut setelah pilihan ditetapkan.",
	"Refine this cultivation path for the current run.": "Murnikan jalur kultivasi ini untuk sesi berjalan.",
	"NEW • LV.1": "BARU • LV.1",
	"ACTIVE RUN • CULTIVATION SEALED": "SESI AKTIF • KULTIVASI TERKUNCI",
	"BATTLE PAUSED": "PERTEMPURAN DIJEDA",
	"Gather your focus. The battlefield remains sealed until you resume.": "Himpun fokusmu. Medan tetap tersegel sampai kamu melanjutkan.",
	"RESUME BATTLE": "LANJUTKAN PERTEMPURAN",
	"SAVE & RETURN HOME": "SIMPAN & KEMBALI KE BERANDA",
	"Returning home preserves the active-run checkpoint.": "Kembali ke beranda mempertahankan checkpoint sesi aktif.",
	"DAO HEART SHAKEN • RUN ENDED": "HATI DAO TERGUNCANG • SESI BERAKHIR",
	"FALLEN IN BATTLE": "GUGUR DALAM PERTEMPURAN",
	"REWARD RECOVERED": "HADIAH DIPULIHKAN",
	"REKINDLE • RETRY": "BANGKIT KEMBALI • COBA LAGI",
	"Retry begins the selected stage from the start. Permanent progression remains intact.": "Coba Lagi memulai ujian terpilih dari awal. Progres permanen tetap tersimpan.",
	"Reflect, refine, and rise again": "Renungkan, murnikan, lalu bangkit kembali",
	"STAGE CLEAR • DAO PATH ADVANCED": "UJIAN TUNTAS • JALAN DAO BERLANJUT",
	"REWARDS SECURED": "HADIAH TERSIMPAN",
	"The run is complete. Rewards are already secured before leaving the battlefield.": "Sesi telah selesai. Hadiah sudah tersimpan sebelum meninggalkan medan pertempuran.",
	"CULTIVATE  •  TRANSCEND  •  ASCEND": "KULTIVASI  •  MELAMPAUI  •  MENCAPAI KEABADIAN",
	"CELESTIAL TRANSIT": "PERJALANAN LANGIT",
	"Opening a passage between realms": "Membuka jalur antaralam",
	"A balanced foundation creates the strongest immortal path.": "Fondasi yang seimbang membentuk jalan keabadian terkuat.",
	"Equipment bonuses remain active throughout every cultivation run.": "Bonus perlengkapan tetap aktif sepanjang setiap sesi kultivasi.",
	"Flying swords answer faster when Swift Qi has been refined.": "Pedang terbang merespons lebih cepat setelah Swift Qi dimurnikan.",
	"Daily quests provide steady resources for patient cultivators.": "Disiplin harian memberi sumber daya stabil bagi kultivator yang tekun.",
	"True ascension is achieved through preparation, not haste.": "Keabadian sejati dicapai melalui persiapan, bukan tergesa-gesa.",
	"REALM": "ALAM",
	"No Chapters are available.": "Belum ada bab yang tersedia.",
	"Select an unlocked realm  •  Cleared progress is permanently recorded": "Pilih alam yang terbuka  •  Progres tuntas tercatat permanen",
	"Unavailable Realm": "Alam Tidak Tersedia",
	"No realm data": "Data alam tidak tersedia",
	"Unknown Realm": "Alam Tidak Dikenal",
	"CHAPTER %02d  •  %s": "BAB %02d  •  %s",
	"CLEARED %d/%d    UNLOCKED %d/%d": "TUNTAS %d/%d    TERBUKA %d/%d",
	"Chapter %d — %s\nCleared %d/%d • Unlocked %d/%d": "Bab %d — %s\nTuntas %d/%d • Terbuka %d/%d",
	"Unavailable": "Tidak Tersedia",
	"Trial data unavailable": "Data ujian tidak tersedia",
	"COMING SOON": "SEGERA HADIR",
	"BOSS GATE": "GERBANG PENJAGA",
	"BOSS • SOON": "PENJAGA • SEGERA",
	"SOON": "SEGERA",
	"Boss Gate": "Gerbang Penjaga",
	"Cultivation Trial": "Ujian Kultivasi",
	"REWARD READY": "HADIAH SIAP",
	"UNLOCKED": "TERBUKA",
	"MAX": "MAKS",
	"DAO CORE": "INTI DAO",
	"Equipment changes are sealed during an active run.": "Perubahan perlengkapan dikunci selama sesi aktif.",
	"UNEQUIP": "LEPAS",
	"Removing an item updates permanent loadout bonuses immediately.": "Melepas item langsung memperbarui bonus perlengkapan permanen.",
	"ITEM NOT OWNED": "ITEM BELUM DIMILIKI",
	"Acquire this equipment before it can be equipped.": "Dapatkan perlengkapan ini sebelum memasangnya.",
	"LOADOUT IMPACT  •  NO CHANGE — CURRENTLY EQUIPPED": "DAMPAK PERLENGKAPAN  •  TANPA PERUBAHAN — SEDANG TERPASANG",
	"LOADOUT IMPACT  •  EQUIP TO APPLY %s": "DAMPAK PERLENGKAPAN  •  PASANG UNTUK MENERAPKAN %s",
	"LOADOUT IMPACT  •  NO STAT CHANGE": "DAMPAK PERLENGKAPAN  •  STAT TIDAK BERUBAH",
	"LOADOUT IMPACT  •  %s": "DAMPAK PERLENGKAPAN  •  %s",
	"LOADOUT IMPACT  •  CHANGES THE SLOT'S STAT PROFILE": "DAMPAK PERLENGKAPAN  •  MENGUBAH PROFIL STAT SLOT",
	"STAT PROFILE CHANGE": "PERUBAHAN PROFIL STAT",
	"NO ACTIVE LOADOUT BONUSES": "TANPA BONUS PERLENGKAPAN AKTIF",
	"%s%.0f MAX HP": "%s%.0f HP MAKS",
	"%s%.0f%% DAMAGE": "%s%.0f%% KERUSAKAN",
	"%s%.0f%% MOVEMENT": "%s%.0f%% GERAK",
	"%s%.0f%% EXP": "%s%.0f%% EXP",
	"%s%.0f%% CRITICAL": "%s%.0f%% KRITIS",
	"PASSIVE EQUIPMENT": "PERLENGKAPAN PASIF",
	"MARTIAL RESONANCE": "RESONANSI BELA DIRI",
	"THIRD-PARTY NOTICES": "PEMBERITAHUAN PIHAK KETIGA",
	"ACTIVE TRIAL IN PROGRESS": "UJIAN AKTIF SEDANG BERJALAN",
	"ABANDON CURRENT TRIAL?": "TINGGALKAN UJIAN SAAT INI?",
	"Selected Trial": "Ujian Terpilih",
	"A saved run already exists. Starting this trial will replace that checkpoint.": "Sesi tersimpan masih ada. Memulai ujian ini akan mengganti checkpoint tersebut.",
	"PERMANENT PROGRESSION IS SAFE": "PROGRES PERMANEN TETAP AMAN",
	"KEEP SAVE": "PERTAHANKAN",
	"START NEW": "MULAI BARU",
	"LEVEL %d • BREAKTHROUGH": "LEVEL %d • TEROBOSAN",
	"WEAPON ART": "JURUS SENJATA",
	"BODY CULTIVATION": "KULTIVASI TUBUH",
	"DAO INSIGHT": "PEMAHAMAN DAO",
	"RESONANCE": "RESONANSI",
	"RESONANCE • UNLOCK": "RESONANSI • BUKA",
	"NEW ART": "JURUS BARU",
	"UPGRADE": "TINGKATKAN",
	"REFINE": "MURNIKAN",
	"MARTIAL FLOW": "ALIRAN BELA DIRI",
	"Power": "Daya",
	"Attack Speed": "Kecepatan Serangan",
	"Movement Speed": "Kecepatan Gerak",
	"Body Refinement": "Pemurnian Tubuh",
	"Spiritual Insight": "Pemahaman Spiritual",
	"Iron Body": "Tubuh Besi",
	"Refine the flying sword that hunts nearby enemies.": "Murnikan pedang terbang yang memburu musuh terdekat.",
	"Strengthen the fire orb launched toward nearby targets.": "Perkuat bola api yang melesat ke sasaran terdekat.",
	"Condense martial force to amplify all outgoing damage.": "Padatkan tenaga bela diri untuk memperkuat seluruh serangan.",
	"Cycle qi faster to shorten the interval between attacks.": "Alirkan Qi lebih cepat untuk memperpendek jeda serangan.",
	"Circulate swift qi through the body to move faster.": "Alirkan Qi lincah melalui tubuh agar bergerak lebih cepat.",
	"Temper the body to expand the vessel of life.": "Tempa tubuh untuk memperbesar daya hidup.",
	"Form a protective qi layer that negates an incoming hit.": "Bentuk lapisan Qi pelindung yang menahan satu serangan.",
	"Command chained lightning through a thunder talisman.": "Kendalikan petir berantai melalui jimat halilintar.",
	"Orbit paired blades around the cultivator to cut nearby foes.": "Putar sepasang bilah di sekeliling kultivator untuk menebas musuh.",
	"Call repeated sword strikes around a chosen enemy.": "Panggil hujan pedang berulang di sekitar musuh terpilih.",
	"Manifest a pulsing formation that damages enemies within it.": "Wujudkan formasi berdenyut yang melukai musuh di dalamnya.",
	"Deepen comprehension to gain more experience from battle.": "Perdalam pemahaman untuk memperoleh lebih banyak pengalaman.",
	"Harden flesh and bone to reduce incoming damage.": "Perkeras daging dan tulang untuk mengurangi luka.",
	"Convert repeated kills into gradual recovery during the run.": "Pulihkan HP secara bertahap dengan mengalahkan musuh.",
	"Sharpen sword intent to increase critical strike chance.": "Pertajam tekad pedang untuk meningkatkan peluang serangan kritis.",
	"Spirit Sword hits can launch a resonance sword toward a secondary enemy.": "Serangan Spirit Sword dapat meluncurkan pedang resonansi ke musuh kedua.",
	"A Qi Shield block awakens a temporary empowered Yin-Yang orbit.": "Blok Qi Shield memperkuat orbit Yin-Yang untuk sementara.",
	"Successful Sword Rain impacts can call down Heavenly Lightning.": "Hantaman Sword Rain dapat memanggil Heavenly Lightning.",
	"+5 BASE DAMAGE": "+5 KERUSAKAN DASAR",
	"+10 BASE DAMAGE": "+10 KERUSAKAN DASAR",
	"+10% DAMAGE POWER": "+10% DAYA SERANGAN",
	"ATTACK COOLDOWN ×0.90": "JEDA SERANGAN ×0,90",
	"MOVEMENT SPEED ×1.10": "KECEPATAN GERAK ×1,10",
	"+2 MAX HP • +2 HP": "+2 HP MAKS • +2 HP",
	"+1 SHIELD CHARGE": "+1 LAPIS PERISAI",
	"GAIN THUNDER TALISMAN": "PEROLEH THUNDER TALISMAN",
	"+4 BASE DAMAGE • CHAIN MILESTONES": "+4 KERUSAKAN DASAR • TAHAP RANTAI",
	"GAIN 2 ORBITING BLADES": "PEROLEH 2 BILAH BERPUTAR",
	"+3 BASE DAMAGE • BLADE MILESTONES": "+3 KERUSAKAN DASAR • TAHAP BILAH",
	"GAIN HEAVENLY SWORD RAIN": "PEROLEH HEAVENLY SWORD RAIN",
	"+4 BASE DAMAGE • STRIKE MILESTONES": "+4 KERUSAKAN DASAR • TAHAP HANTAMAN",
	"GAIN EIGHT TRIGRAMS FORMATION": "PEROLEH EIGHT TRIGRAMS FORMATION",
	"REFINE FORMATION BY LEVEL": "MURNIKAN FORMASI PER LEVEL",
	"+15% EXP MULTIPLIER": "+15% PENGALI EXP",
	"+5% DAMAGE REDUCTION": "+5% PENGURANGAN LUKA",
	"HEAL 1 HP • LOWER KILL THRESHOLD": "PULIHKAN 1 HP • KURANGI SYARAT KILL",
	"+5% CRITICAL CHANCE": "+5% PELUANG KRITIS",
	"SECONDARY SPIRIT SWORD": "SPIRIT SWORD TAMBAHAN",
	"4s EMPOWERED ORBIT AFTER SHIELD BLOCK": "ORBIT MENGUAT 4 DETIK SETELAH BLOK",
	"HEAVENLY LIGHTNING ON SWORD RAIN HIT": "HEAVENLY LIGHTNING SAAT SWORD RAIN MENGENAI",
	"RUN UPGRADE": "PENINGKATAN SESI",
	"RUN-LIMITED UNLOCK": "BERLAKU SELAMA SESI",
	"WAVE %d": "GELOMBANG %d",
	"PHASE %d": "FASE %d",
	"WAVE %d REACHED": "MENCAPAI GELOMBANG %d",
	"SPIRIT STONE BALANCE  •  %s": "SALDO BATU ROH  •  %s",
	"CONTINUE": "LANJUTKAN",
	"ENTER THE TRIAL": "MASUK KE UJIAN",
	"RESUME": "LANJUTKAN",
	"PAUSED": "JEDA",
	"RETURN HOME": "KEMBALI KE BERANDA",
	"RETRY": "COBA LAGI",
	"VICTORY": "KEMENANGAN",
	"DEFEAT": "KEKALAHAN",
	"Returning to Jade Sanctuary": "Kembali ke Pesanggrahan Giok",
	"Returning in Triumph": "Pulang Membawa Kemenangan",
	"Rekindling the Dao Heart": "Membangkitkan Hati Dao",
	"Defeat 20 enemies.": "Kalahkan 20 musuh.",
	"Defeat 50 enemies.": "Kalahkan 50 musuh.",
	"Defeat 100 enemies.": "Kalahkan 100 musuh.",
	"Defeat 250 enemies.": "Kalahkan 250 musuh.",
	"Defeat 1,000 enemies.": "Kalahkan 1.000 musuh.",
	"Reach Level 5 during a run.": "Capai Level 5 dalam satu sesi.",
	"Reach Level 7 during a run.": "Capai Level 7 dalam satu sesi.",
	"Reach Level 10 during a run.": "Capai Level 10 dalam satu sesi.",
	"Reach Level 20 during a run.": "Capai Level 20 dalam satu sesi.",
	"Clear 1 stage.": "Tuntaskan 1 ujian.",
	"Clear 2 stages, including repeats.": "Tuntaskan 2 ujian, termasuk pengulangan.",
	"Clear 3 stages, including repeats.": "Tuntaskan 3 ujian, termasuk pengulangan.",
	"Defeat your first enemy.": "Kalahkan musuh pertamamu.",
	"Clear your first stage.": "Tuntaskan ujian pertamamu.",
	"Defeat your first Stage Boss.": "Kalahkan penjaga ujian pertamamu.",
	"Purchase your first permanent cultivation upgrade.": "Beli peningkatan kultivasi permanen pertamamu.",
	"Clear all five Chapter 1 trials.": "Tuntaskan kelima ujian Bab 1.",
	"Defeat 10 stage guardians.": "Kalahkan 10 penjaga ujian.",
	"Own 10 permanent cultivation levels in total.": "Miliki total 10 level kultivasi permanen.",
	"Refine any combat art to Level 7.": "Murnikan satu jurus hingga Level 7.",
	"CONTINUE  •  C%d  S%d": "LANJUTKAN  •  B%d  U%d",
	"Chapter %d  •  Stage %d-%d": "Bab %d  •  Ujian %d-%d",
	"Stage %d-%d": "Ujian %d-%d",
	"Resuming Cultivation": "Melanjutkan Kultivasi",
	"Restoring the latest checkpoint": "Memulihkan checkpoint terakhir",
	"%d Spirit Stone": "%d Batu Roh",
	"No Reward": "Tanpa Hadiah",
	"No Reward Recovered": "Belum Ada Hadiah",
	"SAVE PENDING": "SIMPANAN TERTUNDA",
	"The Jade Sanctuary welcomes you": "Pesanggrahan Giok menyambutmu",
	"Returning to the battlefield": "Kembali ke medan pertempuran",
	"STAGE CLEAR": "UJIAN TUNTAS",
	"FLOWING STEPS": "LANGKAH MENGALIR",
	"Move Lin Yue to attune with the battlefield. Staying mobile is your first defense.": "Gerakkan Lin Yue untuk menguasai medan. Terus bergerak adalah pertahanan pertamamu.",
	"OBJECTIVE • MOVE TO CONTINUE": "TUJUAN • BERGERAK UNTUK MELANJUTKAN",
	"SELF-MOVING ARTS": "JURUS OTOMATIS",
	"Your equipped weapons strike automatically. Focus on positioning while Spirit Sword hunts nearby enemies.": "Senjatamu menyerang otomatis. Atur posisi sementara Spirit Sword memburu musuh terdekat.",
	"OBJECTIVE • DEFEAT 1 ENEMY": "TUJUAN • KALAHKAN 1 MUSUH",
	"ABSORB SPIRIT ESSENCE": "SERAP ESENSI ROH",
	"Collect essence from fallen enemies. Spirit essence fills EXP and drives your next breakthrough.": "Kumpulkan esensi dari musuh yang tumbang. Esensi mengisi EXP untuk terobosan berikutnya.",
	"OBJECTIVE • GAIN EXP": "TUJUAN • PEROLEH EXP",
	"BREAKTHROUGH": "TEROBOSAN",
	"When EXP is full, time seals itself. Choose one cultivation path to shape this run, then return to battle.": "Saat EXP penuh, waktu berhenti. Pilih satu peningkatan untuk sesi ini, lalu kembali bertempur.",
	"OBJECTIVE • REACH YOUR FIRST BREAKTHROUGH": "TUJUAN • CAPAI TEROBOSAN PERTAMA",
	"ASCENSION TRIAL": "UJIAN KEABADIAN",
	"Foundation forged. Survive the rising waves, refine your build, and defeat the stage guardian.": "Fondasi terbentuk. Bertahan menghadapi gelombang musuh, perkuat jurus, dan kalahkan penjaga ujian.",
	"DAO GUIDANCE COMPLETE": "BIMBINGAN DAO SELESAI",
	"DAO GUIDANCE  •  1 / 5": "BIMBINGAN DAO  •  1 / 5",
	"DAO GUIDANCE  •  2 / 5": "BIMBINGAN DAO  •  2 / 5",
	"DAO GUIDANCE  •  3 / 5": "BIMBINGAN DAO  •  3 / 5",
	"DAO GUIDANCE  •  4 / 5": "BIMBINGAN DAO  •  4 / 5",
	"DAO GUIDANCE  •  5 / 5": "BIMBINGAN DAO  •  5 / 5",
	"CREDITS & LICENSES": "KREDIT & LISENSI",
	"BACK": "KEMBALI",
	"Damage": "Kerusakan",
	"Movement": "Gerak",
	"Critical chance": "Peluang kritis",
	"Critical damage": "Kerusakan kritis",
	"Pickup radius": "Jangkauan serap",
	"Starting shield": "Perisai awal",
	"Blood Qi healing": "Pemulihan Blood Qi",
	"No stat bonus": "Tanpa bonus stat",
	"ASCENSION  •  NO ITEM": "ASCENSION  •  BELUM ADA ITEM",
	"ASCENSION  •  %s  •  REFINEMENT SHARDS %d": "ASCENSION  •  %s  •  PECAHAN PEMURNIAN %d",
	"ASCENSION LOCKED": "ASCENSION TERKUNCI",
	"ASCENSION SEALED": "ASCENSION DISEGEL",
	"MAX ASCENSION": "ASCENSION MAKS",
	"MAX ASCENSION  •  CORE PASSIVE +20% FROM 1★": "ASCENSION MAKS  •  PASIF DASAR +20% DARI 1★",
	"NEXT %d★  •  %s": "BERIKUTNYA %d★  •  %s",
	"ASCEND TO %d★  •  %d SHARDS": "NAIK KE %d★  •  %d PECAHAN",
	"Need %d more Refinement Shards.": "Perlu %d Pecahan Pemurnian lagi.",
	"Acquire this equipment before ascending it.": "Dapatkan perlengkapan ini sebelum menaikkan bintangnya.",
	"Finish or clear the active run before ascending equipment.": "Selesaikan sesi aktif sebelum menaikkan bintang perlengkapan.",
	"Ascension strengthens core passives only; Signature Effects stay fixed.": "Ascension hanya memperkuat pasif dasar; Efek Ciri Khas tetap.",
	"This equipment has reached 5★.": "Perlengkapan ini telah mencapai 5★.",
	"CORE PASSIVE UNCHANGED": "PASIF DASAR TIDAK BERUBAH",
	"SIGNATURE EFFECT  •  NONE": "EFEK CIRI KHAS  •  TIDAK ADA",
	"NO SIGNATURE EFFECT": "TANPA EFEK CIRI KHAS",
	"BLOOD MOON EDGE": "BILAH BULAN DARAH",
	"While at or below 50% HP, final art damage gains +6%.": "Saat HP 50% atau kurang, kerusakan akhir seni bela diri bertambah 6%.",
	"NINEFOLD TEMPO": "IRAMA SEMBILAN LAPIS",
	"Cooldown time is reduced by 6 percent for all weapon arts.": "Waktu jeda semua seni senjata berkurang 6 persen.",
	"RESTORATIVE WARD": "PELINDUNG PEMULIH",
	"Blood Qi restores an additional 0.25 HP per trigger while that art is owned.": "Blood Qi memulihkan tambahan 0,25 HP setiap pemicu selama seni itu dimiliki.",
	"SOVEREIGN WARD": "PELINDUNG PENGUASA",
	"Begin a fresh run with one Qi Shield charge. Continuing never grants another charge.": "Mulai sesi baru dengan satu muatan Perisai Qi. Melanjutkan sesi tidak memberikan muatan tambahan.",
	"STORM BREAK": "PECAH BADAI",
	"Critical hits gain +0.08 to their damage multiplier.": "Serangan kritis mendapat tambahan 0,08 pada pengali kerusakannya.",
	"HEAVENLY EDGE": "BILAH SURGAWI",
	"Critical damage gains +0.15 to its multiplier; normal hits are unaffected.": "Kerusakan kritis mendapat tambahan 0,15 pada pengalinya; serangan normal tidak berubah.",
	"SHADOW MOMENTUM": "MOMENTUM BAYANGAN",
	"While moving, final art damage gains +4%.": "Saat bergerak, kerusakan akhir seni bela diri bertambah 4%.",
	"STARBREATH": "NAPAS BINTANG",
	"Restore 2 HP whenever Lin Yue gains a level.": "Pulihkan 2 HP setiap kali Lin Yue naik level.",
	"CLOUD GATHERING": "HIMPUNAN AWAN",
	"Qi shards begin following you from 48 additional pixels away.": "Pecahan Qi mulai mengikuti dari jarak tambahan 48 piksel.",
	"QI GATHERING": "HIMPUNAN QI",
	"Qi shards begin following you from 24 additional pixels away.": "Pecahan Qi mulai mengikuti dari jarak tambahan 24 piksel.",
	"SWORD HEART": "HATI PEDANG",
	"At or below 50% HP, gain +3 percentage points of critical chance.": "Saat HP 50% atau kurang, dapatkan tambahan 3 poin persentase peluang kritis.",
	"LIVING MERIDIAN": "MERIDIAN HIDUP",
	"Blood Qi restores an additional 0.5 HP per trigger while that art is owned.": "Blood Qi memulihkan tambahan 0,5 HP setiap pemicu selama seni itu dimiliki.",
	"REFINEMENT MATERIAL": "BAHAN PEMURNIAN",
	"Use at Jade Pavilion to forge equipment.": "Gunakan di Paviliun Giok untuk menempa perlengkapan.",
	"Repeat clears and duplicate equipment provide shards. Use them to forge or ascend equipment.": "Penyelesaian ulang dan perlengkapan duplikat menghasilkan pecahan. Gunakan untuk menempa atau menaikkan bintang perlengkapan.",
	"Use this material to forge or ascend equipment.": "Gunakan bahan ini untuk menempa atau menaikkan bintang perlengkapan.",
	"Use Refinement Shards to forge or ascend equipment.": "Gunakan Pecahan Pemurnian untuk menempa atau menaikkan bintang perlengkapan.",
	"Refinement Shard": "Pecahan Pemurnian",
	"OWNED %d UNIQUE  •  %d TOTAL": "DIMILIKI %d JENIS  •  %d TOTAL",
	"EQUIPPED %d / %d": "TERPASANG %d / %d",
	"EQUIPPED": "TERPASANG",
	"IN BACKPACK": "DI DALAM TAS",
	"LOADOUT READY  •  EQUIPMENT MAY BE REFINED": "PERLENGKAPAN SIAP  •  DAPAT DIGANTI",
	"LOADOUT SEALED  •  ACTIVE RUN CHECKPOINT": "PERLENGKAPAN TERKUNCI  •  SESI MASIH AKTIF",
	"LOADOUT SEALED": "PERLENGKAPAN TERKUNCI",
	"NOT OWNED": "BELUM DIMILIKI",
	"EQUIPPED  •  NONE": "TERPASANG  •  KOSONG",
	"EQUIPPED  •  %s  •  %s": "TERPASANG  •  %s  •  %s",
	"NO EQUIPMENT": "TANPA PERLENGKAPAN",
	"No equipment definition is available for this slot.": "Belum ada perlengkapan untuk slot ini.",
	"AWAKENED EFFECT  •  NONE": "EFEK BANGKIT  •  TIDAK ADA",
	"LOADOUT IMPACT  •  NONE": "PERUBAHAN STAT  •  TIDAK ADA",
	"NO ITEM AVAILABLE": "BELUM ADA ITEM",
	"CORE PASSIVE  •  %s  •  Owned x%d": "PASIF DASAR  •  %s  •  Dimiliki x%d",
	"Finish or clear the active run before changing equipment.": "Akhiri sesi aktif sebelum mengganti perlengkapan.",
	"NO AWAKENED EFFECT": "TANPA EFEK BANGKIT",
	"This equipment currently grants its core passive only.": "Perlengkapan ini memberikan pasif dasarnya saja.",
	"DAO ARMAMENT": "SENJATA DAO",
	"DAO PATH": "JALUR DAO",
	"DEFENSIVE PASSIVE": "PASIF PERTAHANAN",
	"OFFENSIVE PASSIVE": "PASIF SERANGAN",
	"MOBILITY PASSIVE": "PASIF GERAK",
	"GROWTH PASSIVE": "PASIF PERTUMBUHAN",
	"JADE EDGE": "BILAH GIOK",
	"BODY WARD": "PERLINDUNGAN TUBUH",
	"MARTIAL FORCE": "TENAGA BELA DIRI",
	"SPIRIT GROWTH": "PERTUMBUHAN ROH",
	"The reward could not be saved. Restart the game to recover.": "Hadiah belum tersimpan. Mulai ulang game untuk memulihkannya.",
	"Restart the game to recover a pending save.": "Mulai ulang game untuk memulihkan simpanan tertunda.",
	"Finish or abandon the current run before forging equipment.": "Selesaikan atau akhiri sesi aktif sebelum menempa perlengkapan.",
	"Insufficient Refinement Shards.": "Pecahan Pemurnian belum cukup.",
	"Insufficient Spirit Stones.": "Batu Roh belum cukup.",
	"The exchange could not be saved. Restart the game to recover.": "Penukaran belum tersimpan. Mulai ulang game untuk memulihkannya.",
	"Wandering Cultivator": "Kultivator Pengembara",
	"Shrinekeeper Aura": "Aura Penjaga Kuil",
	"Sovereign Aura": "Aura Penguasa",
	"An open valley of spirit grass and ancient cultivation markers.": "Lembah terbuka dengan rerumputan roh dan penanda kultivasi kuno.",
	"Valley disciples • Trial Guardian": "Murid lembah • Penjaga Ujian",
	"Mist curls between bamboo groves. Watch the flanks for shadowblades.": "Kabut menyelimuti rumpun bambu. Waspadai penyergap dari samping.",
	"Ranged ambushers • Mobile Mistblade Warden": "Penyergap jarak jauh • Mistblade Warden yang lincah",
	"Broken shrines awaken old wards. Leave the closing seal before it ignites.": "Reruntuhan kuil membangkitkan pelindung lama. Tinggalkan segel sebelum menyala.",
	"Ward keepers • Shrine seals • Jade Shrine Keeper": "Penjaga pelindung • Segel kuil • Jade Shrine Keeper",
	"Wind scours dark jade stone. Dodge marked lightning before the Herald arrives.": "Angin menyapu batu giok gelap. Hindari tanda petir sebelum sang Herald tiba.",
	"Storm Cultivators • Lightning • Stormpeak Herald": "Kultivator badai • Petir • Stormpeak Herald",
	"Cross the golden seals and face the Jade Valley Sovereign's awakened phase.": "Lintasi segel emas dan hadapi fase kebangkitan Jade Valley Sovereign.",
	"Mixed disciples • Celestial seals • Two-phase Sovereign": "Beragam murid • Segel langit • Dua fase Sovereign",
	"ALIGNING SPIRIT VEINS": "MENYELARASKAN NADI ROH",
	"OPENING CELESTIAL GATE": "MEMBUKA GERBANG LANGIT",
	"STABILIZING PASSAGE": "MENSTABILKAN JALUR",
	"PASSAGE STABLE": "JALUR SIAP",
	"Awakening the immortal path": "Membangkitkan jalan keabadian",
	"Every ascendant begins with a single breath of Qi.": "Setiap jalan keabadian dimulai dari satu tarikan Qi.",
	"TRAVERSING THE CELESTIAL PATH": "MELINTASI JALAN LANGIT",
	"DAILY CYCLE  •  ": "SIKLUS HARIAN  •  ",
	"  •  DAILY DISCIPLINE": "  •  DISIPLIN HARIAN",
	"  •  PERMANENT RECORD": "  •  CATATAN PERMANEN",
	"combat": "pertempuran",
	"progression": "progres",
	"journey": "perjalanan",
	"cultivation": "kultivasi",
	"boss": "penjaga",
	"CULTIVATION TRIAL": "UJIAN KULTIVASI",
	"CHAPTER BOSS": "PENJAGA BAB",
	"READY": "SIAP",
	"COMPLETE PRIOR TRIAL": "TUNTASKAN UJIAN SEBELUMNYA",
	"CLEARED • REPLAY AVAILABLE": "TUNTAS • DAPAT DIULANG",
	"First clear": "Pertama tuntas",
	"Replay reward": "Hadiah pengulangan",

	# UI Master Polish B — Trials / Pavilion / Settings / support presentation.
	"Daily Extermination": "Pembersihan Harian",
	"Daily Cultivation": "Kultivasi Harian",
	"Daily Ascension": "Kenaikan Harian",
	"Bamboo Patrol": "Patroli Bambu",
	"Guard the Valley": "Jaga Lembah",
	"Quiet Comprehension": "Pemahaman Hening",
	"Deep Meditation": "Meditasi Mendalam",
	"Walk the Jade Path": "Tapaki Jalan Giok",
	"Three Seals": "Tiga Segel",
	"First Blood": "Darah Pertama",
	"Enemy Slayer": "Pembasmi Musuh",
	"Rising Cultivator": "Kultivator Bangkit",
	"Path Opened": "Jalan Terbuka",
	"Boss Breaker": "Penakluk Penjaga",
	"Cultivation Initiate": "Pemula Kultivasi",
	"Valley Sentinel": "Penjaga Lembah",
	"Thousandfold Intent": "Tekad Seribu Lipat",
	"Qi Condensation": "Kondensasi Qi",
	"Boundless Comprehension": "Pemahaman Tanpa Batas",
	"Sovereign of the Valley": "Penguasa Lembah",
	"Ten Seals Broken": "Sepuluh Segel Terpecah",
	"Meridian Adept": "Ahli Meridian",
	"Sevenfold Art": "Jurus Tujuh Tingkat",
	"Crimson Moon Conqueror": "Penakluk Bulan Merah",
	"Ascendant of Nine Heavens": "Penguasa Sembilan Langit",
	"Jade Ascendant": "Jade Ascendant",
	"Thirty Trials Tempered": "Tiga Puluh Ujian Ditempa",
	"Clear all five Chapter 2 trials.": "Tuntaskan kelima ujian Bab 2.",
	"Clear all five Chapter 3 trials.": "Tuntaskan kelima ujian Bab 3.",
	"Clear all fifteen journey stages.": "Tuntaskan seluruh 15 tahap perjalanan.",
	"Complete 30 stages, including repeats.": "Selesaikan 30 tahap, termasuk pengulangan.",
	"ALL DAILY DISCIPLINES COMPLETE. CLAIM ANY REMAINING REWARDS BEFORE THE NEXT RESET.": "SELURUH DISIPLIN HARIAN SELESAI. AMBIL HADIAH TERSISA SEBELUM RESET BERIKUTNYA.",
	"All daily disciplines complete. Claim any remaining rewards before the next reset.": "Seluruh disiplin harian selesai. Ambil hadiah tersisa sebelum reset berikutnya.",
	"CLAIM ALL  •  %d": "AMBIL SEMUA  •  %d",

	"Sanctum of Refinement": "Sanctum Pemurnian",
	"Meditate • Attune aura • Forge permanent equipment": "Meditasi • Selaraskan aura • Tempa perlengkapan permanen",
	"DAILY RESONANCE": "RESONANSI HARIAN",
	"Meditation": "Meditasi",
	"A quiet breath grants 20 Spirit Stones once per local day.": "Meditasi singkat memberi 20 Batu Roh sekali per hari perangkat.",
	"COSMETIC ATTUNEMENT": "PENYELARASAN KOSMETIK",
	"Realm-clear auras change presentation only. No combat power is hidden here.": "Aura dari penyelesaian alam hanya mengubah tampilan. Tidak ada kekuatan tempur tersembunyi.",
	"Realm-clear auras are free. Postgame prestige auras use earned currencies only and never add combat power.": "Aura dari penyelesaian alam gratis. Aura prestise akhir permainan hanya memakai mata uang hasil bermain dan tidak menambah kekuatan tempur.",
	"PERMANENT LOADOUT": "PERLENGKAPAN PERMANEN",
	"Exchange earned Spirit Stones or Refinement Shards. Duplicate equipment converts to shards automatically.": "Tukar Batu Roh atau Pecahan Pemurnian hasil bermain. Perlengkapan duplikat otomatis menjadi pecahan.",
	"Repeat clears and duplicate equipment provide Refinement Shards for forging.": "Pengulangan tahap dan perlengkapan duplikat memberi Pecahan Pemurnian untuk penempaan.",
	"Repeat clears and duplicate equipment provide shards. Use them at the Jade Pavilion forge.": "Pengulangan tahap dan perlengkapan duplikat memberi pecahan. Gunakan di Penempaan Paviliun Giok.",
	"RARITY": "RARITAS",
	"PLAYER-FIRST EDITION": "EDISI RAMAH PEMAIN",
	"Offline by Design": "Dirancang untuk Luring",
	"All equipment is earned through play. This build has no ads, account requirement, or real-money purchases.": "Semua perlengkapan diperoleh melalui permainan. Tidak ada iklan, akun wajib, atau pembelian uang nyata.",
	"OWNED  •  EQUIP FROM HERO": "DIMILIKI  •  PASANG DARI HERO",
	"LOCKED  •  CLEAR %d-%d": "TERKUNCI  •  TUNTASKAN %d-%d",
	"%d STONES": "%d BATU ROH",
	"%d SHARDS": "%d PECAHAN",
	"ATTUNED  ✓": "TERSELARAS  ✓",
	"SAVE RECOVERY REQUIRED  •  REOPEN THE GAME BEFORE CHANGING LOADOUT": "SIMPANAN PERLU DIPULIHKAN  •  BUKA ULANG GAME SEBELUM MENGUBAH PERLENGKAPAN",
	"FORGE SEALED  •  FINISH THE ACTIVE RUN TO MODIFY PERMANENT EQUIPMENT": "PENEMPAAN TERKUNCI  •  SELESAIKAN SESI AKTIF UNTUK MENGUBAH PERLENGKAPAN",
	"SANCTUM READY  •  PERMANENT PROGRESSION IS SAFE": "SANCTUM SIAP  •  PROGRES PERMANEN AMAN",
	"Aura attuned.": "Aura diselaraskan.",
	"Astral Crown Aura": "Aura Mahkota Astral",
	"Jade Ascendant Halo": "Halo Jade Ascendant",
	"OWNED  •  ATTUNE": "DIMILIKI  •  SELARASKAN",
	"CLEAR %d-%d": "TUNTASKAN %d-%d",
	"REQUIRES %s": "MEMERLUKAN %s",
	"%d STONES + %d SHARDS": "%d BATU ROH + %d PECAHAN",
	"Aura acquired and attuned.": "Aura diperoleh dan diselaraskan.",
	"Complete the required ascension path before attuning this aura.": "Tuntaskan jalur keabadian yang disyaratkan sebelum menyelaraskan aura ini.",
	"Acquire this aura before attuning it.": "Peroleh aura ini sebelum menyelaraskannya.",

	"COMFORT": "KENYAMANAN",
	"Combat Presentation": "Tampilan Pertempuran",
	"Tune motion and combat feedback without changing game balance.": "Atur gerakan dan umpan balik tempur tanpa mengubah keseimbangan permainan.",
	"Reduced flashes & effects": "Kurangi kilatan & efek",
	"Vibration feedback": "Umpan balik getaran",
	"SYSTEM": "SISTEM",
	"Display & Language": "Tampilan & Bahasa",
	"Choose the performance target and interface language for this device.": "Pilih target performa dan bahasa antarmuka perangkat ini.",
	"60 FPS  •  SMOOTH": "60 FPS  •  HALUS",
	"30 FPS  •  BATTERY SAVER": "30 FPS  •  HEMAT BATERAI",
	"PRIVACY, SUPPORT & CREDITS": "PRIVASI, BANTUAN & KREDIT",

	"PLAYER TRUST": "KEPERCAYAAN PEMAIN",
	"Privacy & Support": "Privasi & Bantuan",
	"LOCAL-FIRST": "UTAMA LOKAL",
	"What stays private": "Yang tetap privat",
	"ON-DEVICE SAVE": "SIMPANAN PERANGKAT",
	"What the game stores": "Data yang disimpan game",
	"DATA CONTROL": "KONTROL DATA",
	"OPTIONAL FEEDBACK": "UMPAN BALIK OPSIONAL",
	"EXTERNAL APPS": "APLIKASI EKSTERNAL",
	"Links & support": "Tautan & bantuan",
	"SUPPORT": "BANTUAN",
	"ARCHIVE": "ARSIP",
	"Credits & Licenses": "Kredit & Lisensi",
	"Jade Ascendant • Open-source notices and acknowledgements": "Jade Ascendant • Pemberitahuan sumber terbuka dan penghargaan",
	"BACK TO PRIVACY": "KEMBALI KE PRIVASI",
	"CLEAR 1-%d": "TUNTASKAN 1-%d"
}

func _enter_tree() -> void:
	var translation: Translation = Translation.new()
	translation.locale = "id"
	for message in INDONESIAN:
		translation.add_message(str(message), str(INDONESIAN[message]))
	TranslationServer.add_translation(translation)
