extends RefCounted

static var _installed: bool = false

const INDONESIAN: Dictionary = {
	"MAIL": "SURAT",
	"7-DAY": "7 HARI",
	"EVENTS": "EVENT",
	"TREASURY": "TREASURY",

	"LIVE SERVICES": "LAYANAN LANGIT",
	"Mailbox": "Kotak Surat",
	"Messages, gifts, and system notices from the Jade Sanctuary.": "Pesan, hadiah, dan pemberitahuan dari Pesanggrahan Giok.",
	"NO MAIL": "TIDAK ADA SURAT",
	"Your mailbox is empty.": "Kotak suratmu kosong.",
	"JADE SANCTUARY": "PESANGGRAHAN GIOK",
	"CELESTIAL PAVILION": "PAVILIUN LANGIT",
	"Welcome, Wandering Cultivator": "Selamat Datang, Kultivator Pengembara",
	"Your first steps on the immortal path have begun. Accept these supplies and prepare for the trials ahead.": "Langkah pertamamu di jalan keabadian telah dimulai. Terima bekal ini dan bersiap menghadapi ujian.",
	"Seven Days of Ascension": "Tujuh Hari Menuju Keabadian",
	"Return on seven active days to unlock newcomer supplies. Missed calendar days do not erase your progress.": "Kembali pada tujuh hari aktif untuk membuka bekal pemain baru. Hari kalender yang terlewat tidak menghapus progresmu.",
	"ATTACHMENT": "LAMPIRAN",
	"CLAIM ATTACHMENT": "AMBIL LAMPIRAN",
	"CLAIMED": "DIAMBIL",
	"READ": "DIBACA",
	"‹  HOME": "‹  BERANDA",

	"NEW CULTIVATOR EVENT": "EVENT KULTIVATOR BARU",
	"Seven active days. No calendar punishment. Your progress waits for you.": "Tujuh hari aktif. Tidak ada hukuman karena melewatkan hari kalender. Progresmu tetap menunggu.",
	"ACTIVE DAY %d / %d": "HARI AKTIF %d / %d",
	"DAY %d": "HARI %d",
	"AVAILABLE": "TERSEDIA",
	"LOCKED": "TERKUNCI",
	"CLAIM REWARD": "AMBIL HADIAH",
	"UNLOCKS ON ACTIVE DAY %d": "TERBUKA PADA HARI AKTIF %d",
	"ALL SEVEN DAYS COMPLETE": "TUJUH HARI SELESAI",
	"Your newcomer journey is complete. Keep ascending.": "Perjalanan pemain barumu selesai. Teruslah menapaki jalan keabadian.",

	"EVENT CENTER": "PUSAT EVENT",
	"Celestial Events": "Event Langit",
	"Live activities and returning-player reasons without cluttering the sanctuary.": "Aktivitas berkala dan alasan untuk kembali bermain tanpa memenuhi layar utama.",
	"NEW PLAYER": "PEMAIN BARU",
	"Open Seven Days": "BUKA TUJUH HARI",
	"DAILY": "HARIAN",
	"Daily Cultivation": "Kultivasi Harian",
	"Complete daily disciplines and settle available rewards.": "Selesaikan disiplin harian dan ambil hadiah yang tersedia.",
	"OPEN DAILY TRIALS": "BUKA UJIAN HARIAN",
	"OPTIONAL": "OPSIONAL",
	"Celestial Patronage": "Dukungan Langit",
	"Optional rewarded ads remain inside the Pavilion and never block progression.": "Iklan berhadiah opsional tetap berada di Paviliun dan tidak menghalangi progres.",
	"OPEN PAVILION": "BUKA PAVILIUN",
	"%d REWARD READY": "%d HADIAH SIAP",
	"%d REWARDS READY": "%d HADIAH SIAP",
	"COMPLETED": "SELESAI",

	# Event Production final presentation catalog.
	"LIVE OPS": "EVENT LANGIT",
	"EVENT": "EVENT",
	"JADE ASCENDANT  /  LIVE EVENTS": "JADE ASCENDANT  /  EVENT LANGIT",
	"JADE ASCENDANT  /  EVENTS": "JADE ASCENDANT  /  EVENT",
	"CELESTIAL EVENTS": "EVENT LANGIT",
	"FEATURED EVENT": "EVENT UNGGULAN",
	"FEATURED": "UNGGULAN",
	"EVENT ACTIVE": "EVENT AKTIF",
	"EVENT REWARDS ARE CLAIMED IN THEIR OWN SCREENS": "HADIAH EVENT DIAMBIL DI LAYAR MASING-MASING",
	"SEVEN DAYS OF ASCENSION": "TUJUH HARI MENUJU KEABADIAN",
	"Continue your cultivation journey and collect the rewards you have earned.": "Lanjutkan perjalanan kultivasimu dan ambil hadiah yang telah kamu raih.",
	"CHECKING EVENT": "MEMERIKSA EVENT",
	"OPEN EVENT  ›": "BUKA EVENT  ›",
	"YOUR CULTIVATION ACTIVITIES": "AKTIVITAS KULTIVASIMU",
	"Daily Trials": "Ujian Harian",
	"DAILY CULTIVATION": "KULTIVASI HARIAN",
	"Complete daily disciplines and collect available rewards.": "Selesaikan disiplin harian dan ambil hadiah yang tersedia.",
	"OPEN DAILY  ›": "BUKA HARIAN  ›",
	"Celestial Pavilion": "Paviliun Langit",
	"OPTIONAL ACTIVITIES": "AKTIVITAS OPSIONAL",
	"Discover Pavilion services and optional rewarded activities.": "Temukan layanan Paviliun dan aktivitas berhadiah opsional.",
	"OPEN PAVILION  ›": "BUKA PAVILIUN  ›",
	"DAY %d / %d": "HARI %d / %d",
	"%d READY": "%d SIAP",
	"IN PROGRESS": "BERLANGSUNG",

	"JOURNEY EVENT": "EVENT PERJALANAN",
	"JADE VALLEY PILGRIMAGE": "ZIARAH LEMBAH GIOK",
	"Clear key trials across Verdant Qi Valley and claim pilgrimage offerings.": "Selesaikan ujian penting di Lembah Qi Hijau dan ambil persembahan ziarah.",
	"OPEN PILGRIMAGE  ›": "BUKA ZIARAH  ›",
	"VERDANT MILESTONES": "MILESTONE LEMBAH HIJAU",
	"PROGRESS %d / %d": "PROGRES %d / %d",
	"BAMBOO MIST PASSAGE": "JALUR KABUT BAMBU",
	"STORM PEAK OATH": "SUMPAH PUNCAK BADAI",
	"SOVEREIGN GATE": "GERBANG SANG PENGUASA",
	"Clear Stage 1-2: Bamboo Mist Pass.": "Selesaikan Stage 1-2: Jalur Kabut Bambu.",
	"Clear Stage 1-4: Storm Peak Approach.": "Selesaikan Stage 1-4: Pendekatan Puncak Badai.",
	"Clear Stage 1-5: Sovereign's Celestial Gate.": "Selesaikan Stage 1-5: Gerbang Langit Sang Penguasa.",
	"CLEAR STAGE 1-%d": "SELESAIKAN STAGE 1-%d",
	"ALL PILGRIMAGE OFFERINGS CLAIMED": "SEMUA PERSEMBAHAN ZIARAH SUDAH DIAMBIL",

	"BOSS HUNT EVENT": "EVENT PERBURUAN BOS",
	"CELESTIAL BOSS HUNT": "PERBURUAN BOS LANGIT",
	"Defeat the sovereign at the end of each realm and claim one-time celestial bounties.": "Kalahkan penguasa di akhir setiap alam dan ambil bounty langit satu kali.",
	"OPEN BOSS HUNT  ›": "BUKA PERBURUAN BOS  ›",
	"SOVEREIGN BOUNTIES": "BOUNTY PARA PENGUASA",
	"VERDANT SOVEREIGN BOUNTY": "BOUNTY PENGUASA LEMBAH HIJAU",
	"CRIMSON MOON BOUNTY": "BOUNTY BULAN MERAH",
	"STAR PALACE BOUNTY": "BOUNTY ISTANA BINTANG",
	"FROSTBOUND BOUNTY": "BOUNTY PENGUASA EMBUN BEKU",
	"PRIMORDIAL SUN BOUNTY": "BOUNTY MATAHARI PURBA",
	"Clear Stage 1-5 and defeat the Jade Valley Sovereign.": "Selesaikan Stage 1-5 dan kalahkan Penguasa Lembah Giok.",
	"Clear Stage 2-5 and defeat the Crimson Moon Sect Master.": "Selesaikan Stage 2-5 dan kalahkan Master Sekte Bulan Merah.",
	"Clear Stage 3-5 and defeat the Star Palace Celestial Sovereign.": "Selesaikan Stage 3-5 dan kalahkan Penguasa Langit Istana Bintang.",
	"Clear Stage 4-5 and defeat the Frostbound Sovereign.": "Selesaikan Stage 4-5 dan kalahkan Penguasa Embun Beku.",
	"Clear Stage 5-5 and defeat the Primordial Sun Sovereign.": "Selesaikan Stage 5-5 dan kalahkan Penguasa Matahari Purba.",
	"CLAIM 2× • OPTIONAL AD": "AMBIL 2× • IKLAN OPSIONAL",
	"2× BOOST AVAILABLE TODAY": "BOOST 2× TERSEDIA HARI INI",
	"2× BOOST USED TODAY": "BOOST 2× SUDAH DIPAKAI HARI INI",
	"2× BOOST UNAVAILABLE": "BOOST 2× BELUM TERSEDIA",
	"2× BOOST IN PROGRESS": "BOOST 2× SEDANG BERJALAN",
	"NORMAL CLAIM ALWAYS REMAINS AVAILABLE": "KLAIM NORMAL SELALU TETAP TERSEDIA",
	"CLEAR STAGE %d-5": "SELESAIKAN STAGE %d-5",
	"ALL BOSS BOUNTIES CLAIMED": "SEMUA BOUNTY BOS SUDAH DIAMBIL",
	"LADDER EVENT": "EVENT TANGGA LANGIT",
	"HEAVENLY LADDER": "TANGGA LANGIT",
	"Clear stages across every realm and ascend the Heavenly Ladder for one-time rewards.": "Selesaikan stage di setiap alam dan naiki Tangga Langit untuk hadiah satu kali.",
	"OPEN LADDER  ›": "BUKA TANGGA  ›",
	"ASCENSION RUNGS": "ANAK TANGGA ASCENSION",
	"FIRST ASCENT": "PENDAKIAN PERTAMA",
	"CLOUD STEP": "LANGKAH AWAN",
	"JADE STAIR": "TANGGA GIOK",
	"STARWARD STEP": "LANGKAH MENUJU BINTANG",
	"HEAVEN GATE": "GERBANG LANGIT",
	"CELESTIAL ARCH": "LENGKUNG LANGIT",
	"SOVEREIGN HEIGHT": "PUNCAK PENGUASA",
	"ASCENDANT SUMMIT": "PUNCAK ASCENDANT",
	"CLEAR %d JOURNEY STAGES": "SELESAIKAN %d STAGE PERJALANAN",
	"ALL LADDER REWARDS CLAIMED": "SEMUA HADIAH TANGGA SUDAH DIAMBIL",

	"✦  SEVEN-DAY BLESSING  ✦": "✦  BERKAH TUJUH HARI  ✦",
	"CELESTIAL SIGN-IN": "ABSEN LANGIT",
	"Seven active days. Your ascension awaits.": "Tujuh hari aktif. Jalan ascension-mu menanti.",
	"ASCENSION PATH": "JALUR ASCENSION",
	"%d/%d ACTIVE": "%d/%d AKTIF",
	"←  SWIPE FOR DAYS 1–7  →": "←  GESER UNTUK HARI 1–7  →",
	"✓ CLAIMED": "✓ DIAMBIL",
	"✦ READY": "✦ SIAP",
	"◈ LOCKED": "◈ TERKUNCI",
	"+%d SHARDS": "+%d PECAHAN",
	"STONES": "BATU SPIRIT",
	"SPIRIT STONES": "BATU SPIRIT",
	"REFINEMENT SHARDS": "PECAHAN PEMURNIAN",
	"DAY 07  •  THE SEVENTH GATE": "HARI 07  •  GERBANG KETUJUH",
	"DAY %02d  •  ASCENSION REWARD": "HARI %02d  •  HADIAH ASCENSION",
	"READY TO CLAIM": "SIAP DIAMBIL",
	"SEALED  •  RETURN ON THIS ACTIVE DAY": "TERSEGEL  •  KEMBALI PADA HARI AKTIF INI",
	"CLAIM FINAL GIFT": "AMBIL HADIAH TERAKHIR",
	"UNLOCK ON DAY %d": "TERBUKA PADA HARI %d",
	"SAVING UNAVAILABLE": "PENYIMPANAN TIDAK TERSEDIA",
	"REWARDS SAVE ON CLAIM": "HADIAH TERSIMPAN SAAT DIAMBIL",
	"CLAIM UNAVAILABLE": "HADIAH BELUM BISA DIAMBIL",

	"JADE SANCTUARY  ·  CELESTIAL COURIER": "PESANGGRAHAN GIOK  ·  KURIR LANGIT",
	"SPIRIT MESSAGES": "PESAN SPIRIT",
	"Messages from across the Cultivation World": "Pesan dari seluruh Dunia Kultivasi",
	"INBOX": "KOTAK MASUK",
	"SYSTEM MAIL": "SURAT SISTEM",
	"%d LETTER": "%d SURAT",
	"%d LETTERS": "%d SURAT",
	"NEW": "BARU",
	"NOTICE": "PEMBERITAHUAN",
	"ATTACHMENTS": "LAMPIRAN",
	"SEALED NOTICE": "PEMBERITAHUAN TERSEGEL",
	"MESSAGE · NO REWARD": "PESAN · TANPA HADIAH",
	"ATTACHMENT CLAIMED": "LAMPIRAN DIAMBIL",
	"UNCLAIMED ATTACHMENT": "LAMPIRAN BELUM DIAMBIL",
	"OFFICIAL NOTICE": "PEMBERITAHUAN RESMI",
	"FROM · ": "DARI · ",
	"SAVE READ ONLY": "SAVE HANYA-BACA",
	"CLAIM": "AMBIL",
	"CLAIM FAILED · RETRY": "GAGAL MENGAMBIL · COBA LAGI",
	"WAITING FOR A LETTER": "MENUNGGU SURAT",
	"NO ATTACHMENTS": "TANPA LAMPIRAN",
	"NOTICE · NO ATTACHMENT": "PEMBERITAHUAN · TANPA LAMPIRAN",
	"The Empty Sky": "Langit yang Sepi",
	"No letters have arrived.\n\nThe Celestial Courier awaits.": "Belum ada surat yang tiba.\n\nKurir Langit masih menunggu.",
	"No messages have arrived.\n\nMay the Celestial Courier bring good tidings to your cultivation path.": "Belum ada pesan yang tiba.\n\nSemoga Kurir Langit membawa kabar baik untuk jalan kultivasimu.",

	"STORE PREVIEW": "PRATINJAU TOKO",
	"Celestial Treasury": "Treasury Langit",
	"Google Play prices will be localized by the store when Billing is connected.": "Harga Google Play akan mengikuti mata uang lokal saat Billing terhubung.",
	"DEBUG PREVIEW • PURCHASES DISABLED": "PRATINJAU DEBUG • PEMBELIAN DINONAKTIFKAN",
	"CURRENT BALANCE": "SALDO SAAT INI",
	"%d CELESTIAL JADE": "%d GIOK LANGIT",
	"%d PAVILION SEALS": "%d SEGEL PAVILIUN",
	"JADE POUCH": "KANTONG GIOK",
	"JADE SATCHEL": "TAS GIOK",
	"JADE CASKET": "PETI GIOK",
	"JADE VAULT": "BRANKAS GIOK",
	"JADE TREASURY": "TREASURY GIOK",
	"ASCENDANT RESERVE": "CADANGAN ASCENDANT",
	"STARTER SUPPORT PACK": "PAKET DUKUNGAN PEMULA",
	"MONTHLY JADE BLESSING": "BERKAH GIOK BULANAN",
	"%d JADE": "%d GIOK",
	"%d JADE + %d SEALS": "%d GIOK + %d SEGEL",
	"%d JADE NOW + %d/DAY • %d DAYS": "%d GIOK SEKARANG + %d/HARI • %d HARI",
	"BILLING NEXT": "BILLING BERIKUTNYA",
	"Prices are intentionally not hardcoded.": "Harga sengaja tidak ditulis langsung di dalam game.",
	"CELESTIAL TREASURY": "TREASURY LANGIT",
	"Prices are loaded directly from Google Play. No price is hardcoded.": "Harga dimuat langsung dari Google Play. Tidak ada harga yang ditulis manual.",
	"GOOGLE PLAY BILLING • CHECKING": "GOOGLE PLAY BILLING • MEMERIKSA",
	"GOOGLE PLAY BILLING • READY": "GOOGLE PLAY BILLING • SIAP",
	"GOOGLE PLAY BILLING • %s": "GOOGLE PLAY BILLING • %s",
	"Purchases are optional and do not block progression.": "Pembelian bersifat opsional dan tidak menghalangi progres.",
	"RESTORE PURCHASES": "PULIHKAN PEMBELIAN",
	"PRICE FROM GOOGLE PLAY": "HARGA DARI GOOGLE PLAY",
	"CHECKING STORE...": "MEMERIKSA TOKO...",
	"COMING LATER • PURCHASE FLOW NOT ENABLED YET": "SEGERA HADIR • ALUR PEMBELIAN BELUM DIAKTIFKAN",
	"NOT AVAILABLE YET": "BELUM TERSEDIA",
	"COMING LATER": "SEGERA HADIR",
	"OWNED": "SUDAH DIMILIKI",
	"PURCHASED": "SUDAH DIBELI",
	"PURCHASE • %s": "BELI • %s",
	"OPENING GOOGLE PLAY...": "MEMBUKA GOOGLE PLAY...",
	"Waiting for Google Play purchase result...": "Menunggu hasil pembelian dari Google Play...",
	"Purchase is not available right now.": "Pembelian belum tersedia saat ini.",
	"Checking Google Play for recoverable purchases...": "Memeriksa pembelian yang dapat dipulihkan dari Google Play...",
	"PURCHASE SAVED • REWARD DELIVERED": "PEMBELIAN TERSIMPAN • HADIAH DITERIMA",
	"UNAVAILABLE": "TIDAK TERSEDIA",
}


static func install() -> void:
	if _installed:
		return
	var translation := Translation.new()
	translation.locale = "id"
	for raw_message_id in INDONESIAN:
		var message_id: String = str(raw_message_id)
		translation.add_message(
			message_id,
			str(INDONESIAN[message_id])
		)
	TranslationServer.add_translation(translation)
	_installed = true
